- libsrc/bonjour/bonjourserviceregister.cpp
- src/hyperiond/main.cpp
It was missing a )
setenv("AVAHI_COMPAT_NOWARN", "1", 1);
> Fixed compile error when no grabbers are defined + remove avahi warning

- src/hyperiond/hyperiond.cpp
added "enable" : true/false to both udp listener and boblight
Changed the zeroconf/mDNS service names
"boblightServer" :
{
"enable" : false,
"port" : 19333
},
"udpListener" :
{
"enable" : true,
"port" : 2801,
"priority" : 880,
"timeout"  : 5000
},
You can no longer configure the mDNSDescr nor mDNSname from the json configuration
> add "enable" : true/false to both udp listener and boblight, zeroconf cleanup

- include/boblightserver/BoblightServer.h
- include/udplistener/UDPListener.h
- libsrc/boblightserver/BoblightServer.cpp
- libsrc/udplistener/UDPListener.cpp
- src/hyperiond/hyperiond.cpp
- src/hyperiond/hyperiond.h
- src/hyperiond/main.cpp
rework bootsequence settings and behaviour.
others:
a small fix in hyperiond: dispmanx grabber was created twice
boblight/udplistener now uses hyperion::getInstance
webserver is alive when daemon crashes (atm not in every situation, because of evil exit() commands in e.g. leddeviceFactory)
yes :-)
bootsequence block is gone, new initialEffect should be inserted:
```
"initialEffect" : 
{
"background-effect" : [136, 97, 50 ],
"foreground-effect" : "Rainbow swirl fast",
"foreground-duration_ms" : 3000
},
```
You can set a color RGB value or a string with effect name. There is no priority settings anymore!!!
Foreground effect/color is set to highest prio (0) as the …
> rework bootsequence

- include/utils/Logger.h
- libsrc/utils/Logger.cpp
- src/hyperiond/main.cpp
Add ability to set loglevel for all loggers and for specific loggers.
Example:
```
// will set min log level for all loggers to warning
Logger::setLogLevel(Logger::WARNING);
// will set loglevel of specific logger to warning
// if global log level is set (above) this is useless
Logger::setLogLevel(Logger::WARNING, ”EFFECT”);
```
Next step is to connect this with config ....
No
> logger: set global log level

- include/udplistener/UDPListener.h
- libsrc/udplistener/UDPListener.cpp
- src/hyperiond/hyperiond.cpp
native UDP listener enhancements
- uses new logger
- can specifiy which ip address to listen on
- if its a multicast address, multicast is enabled
The address option is new and optional, default is listen on all ip addresses
"udpListener" :
{
"enable" : true,
//              "address" : "239.255.28.01",
//              "address" : "10.0.0.72",
//              "address" : "10.0.0.7",
//              "address" : "0.0.0.0",
"port" : 2801,
"priority" : 800,
"timeout"  : 5000
},
- uses new logger
- can specifiy which ip address to listen on
- if its a multicast …
> native UDP listener enhancements

- include/udplistener/UDPListener.h
- libsrc/udplistener/UDPListener.cpp
- src/hyperiond/hyperiond.cpp
- if you listen to a multicast address, it now also listens to all ipv4 addresses
- shared udp sockets - multiple hyperiond instance can optionally share the same udp packets
False is the defaul
"shared" : true
> UDPListener improvements:

- cmake/debian/postinst
the default config was renamed - this produced an error in debian postinstall. @brindosch please change config name in cmake/debian/postinst if you change the config name again.
> fix config install in deb package

- include/udplistener/UDPListener.h
- libsrc/udplistener/UDPListener.cpp
eg: configure 42 leds, but a udp packet only contains 10 leds, the remaining 32 are now set to black
no
#54 
> udplistener will now set remaining LEDs to black.

- libsrc/leddevice/LedDeviceFactory.cpp
- libsrc/leddevice/LedDeviceFadeCandy.cpp
- libsrc/leddevice/LedDeviceFadeCandy.h
extend Fadecandy driver to set all hardware/fcserver config data. 
yes, if fadecandy device is used.
valid config block is shown in LedDeviceFadeCandy.h as doxygen doc
```
"device" :
{
"name"          : "MyPi",
"type"          : "fadecandy",
"output"        : "localhost",
"colorOrder"    : "rgb",
"gamma"         : 1.0,
"whitepoint"    : [1.0, 1.0, 1.0],
"dither"        : false,
"interpolation" : false,
"manualLed"     : false,
"ledOn"         : false
}, 
```
> extend Fadecandy driver

- .travis/travis_install.sh
- config/hyperion.config.json.commented
- config/hyperion.config.json.default
- include/leddevice/LedDevice.h
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/LinearColorSmoothing.cpp
- libsrc/hyperion/LinearColorSmoothing.h
- libsrc/leddevice/LedDevice.cpp
- libsrc/leddevice/LedDeviceFactory.cpp
- libsrc/leddevice/LedDeviceFadeCandy.cpp
- libsrc/leddevice/LedDeviceFadeCandy.h
- libsrc/leddevice/LedDeviceLightpack.cpp
- libsrc/leddevice/LedDeviceLightpack.h
- libsrc/leddevice/LedDeviceMultiLightpack.cpp
- refactoring leddevicefactory
- adalight: default for "delayAfterConnect" is 1s now - needed for most arduino's because of there special behaviour on open
- fadecandy: new option for disabling configuration send - if you want to keep your fadecandy defaults
- Hyperion.cpp: simplify createSmoothing discussed in #105
- smoothing:
- add option for continuous output
- when updatedelay>0 and continousOutput is disabled, buffer is flushed correctly after no input is detected
- ad doxygen to travis
yes, smoothing gets a new param `"continuousOutput" : false`
#111 #87
> multi fix commit

- config/hyperion.config.json.commented
- config/hyperion.config.json.default
- src/hyperiond/hyperiond.cpp
- some optimizations, sadly you need for kodi the enabled remote option, cause of this i suggest to disable it.
- raised a little bit the grabber value (value of 16) to take account of the usage of more leds
- raised smoothing from 20 to 25 fps to prevent stutter (assumed SPI/PWM gpio) this won't work for all devices.
Issue https://github.com/hyperion-project/hyperion.ng/issues/3
> Add enable option to grabbers

- .travis/travis_build.sh
add tiny test framework to run on travis or on local host
to run on your maschine:
cd into your hyperion folder.
call: bash .travis/travis_build.sh
I enabled the cmake warnings - we definitely want to see the warnings - to solve them
> add tiny test framework to run on travis or on local host

- include/grabber/V4L2Grabber.h
- include/grabber/V4L2Wrapper.h
- libsrc/grabber/v4l2/V4L2Grabber.cpp
- libsrc/grabber/v4l2/V4L2Wrapper.cpp
- src/hyperion-v4l2/hyperion-v4l2.cpp
- src/hyperiond/hyperiond.cpp
as the title said: hyperion won't fail, if v4l2 has invalid device.
If invalid device is detected, error messages is printed and v4l2 capture device is disabled.
and add auto device: uses the first valid device. Set "auto" as device in config
```
"grabber-v4l2" : 
{
"enable" : true,
"device" : "auto",
```
Instead ”/dev/video0” type ”auto”
> hyperion won't fail, if v4l2 has invalid device + auto device

- include/blackborder/BlackBorderProcessor.h
- include/hyperion/ImageProcessor.h
- libsrc/blackborder/BlackBorderProcessor.cpp
- libsrc/effectengine/Effect.cpp
- libsrc/hyperion/ImageProcessor.cpp
... make "enable" work for blackborder detector
If you look with --debug, then you will see following message in state enabled=false too:
`//[HYPERIOND BLACKBORDER] <DEBUG> <BlackBorderDetector.cpp:26:calculateThreshold()> threshold set to 0.000000 (0)`
bb is deactivated, but the bb detector object is created - but do nothing, just prints that line. If you enable bb, then you will see more messages ....
#3 #107 
> make "enable" work for blackborder detector

- src/hyperiond/main.cpp
If you are grepping the debugging output and then hit ctrl-C, theres a good chance hyperiond never cleans up properly.
> Added SIGPIPE handing.

- libsrc/utils/Logger.cpp
make logger don't crash when long messages put to logger. Currently longest message is 1024 chars. Longer messages are truncated
#131
> fix logger crash

- include/kodivideochecker/KODIVideoChecker.h
- libsrc/kodivideochecker/KODIVideoChecker.cpp
Es sollten jetzt alle zustände (Video, Audio, Picture, Pause, Menu, Screensaver) von Kodi erfasst werden. Auch wenn sich Kodi im Anmeldemodus befindet (Passwort). Der Pause zustand wird nun auch richtig erkannt, nach dem der screensaver aktiviert oder daktiviert wird.
Feedback ist erwünscht.
no
> KODIVideoChecker Fix

- libsrc/grabber/v4l2/V4L2Grabber.cpp
fix error found in #118 usable v4l device was opened twice
> v4l: fix auto mode opens usable device twice

- libsrc/utils/jsonschema/QJsonSchemaChecker.cpp
Leider ein Denkfehler.
Der "Required" Schlüssel wurde mit sich selbst verglichen.
Jetzt sollte der Vergleich zwischen Schema und Config so funktionieren wie vorgesehen.
Hier noch mal kurz erklärt:
Ist der Required Schlüssel im Schema "true" MUSS dieser Eintrag in der Config Datei vorhanden sein.
Ist der Required Schlüssel im Schema "false" MUSS dieser Eintrag NICHT zwingend in der Config Datei vorhanden sein.
> Fixing "Required" Key in QJsonSchemaChecker

- libsrc/grabber/amlogic/AmlogicWrapper.cpp
- libsrc/grabber/v4l2/V4L2Grabber.cpp
- libsrc/jsonserver/JsonClientConnection.cpp
- src/hyperiond/hyperiond.cpp
- src/hyperiond/hyperiond.h
**Amlogic box uses aml and fb buffer**
on amlogic (wetek) systems you need 2 grabbers. aml and fb. Now both are started, with same settings. This is the same as before adding the amlgrabber section with same settings of framegabber section. The prio of aml is decreased by 1, because aml and fb arn't allowed to e on same channel.
In framegrabber section set type to "auto" or "amlogic". If you want FB only use "framebuffer" as type.
**hyperiond**
refactoring of hyperiond.cpp grabber config code.
**json client**
now all input sources (grabber, network, effects) are shown in hyperion-remote --list. Entries marked as active=true/false to show their state.
example:
```
"priorities" : [
{
"active" : "true",
"duration_ms" : 178,
"owner" : "X11 …
```
> Amlogic box uses aml and fb buffer

- include/hyperion/Hyperion.h
- include/jsonserver/JsonServer.h
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/PriorityMuxer.cpp
- libsrc/hyperion/hyperion.schema.json
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/jsonserver/JsonClientConnection.h
- libsrc/jsonserver/JsonSchemas.qrc
- libsrc/jsonserver/JsonServer.cpp
- libsrc/jsonserver/schema/schema-sourceselect.json
- libsrc/jsonserver/schema/schema.json
- src/hyperion-remote/JsonConnection.cpp
- src/hyperion-remote/JsonConnection.h
- src/hyperion-remote/hyperion-remote.cpp
currently input sources (grabbers, effect, udplistener ...) are selected by an automatic priority mechanism. Now it is possible to override this mechanism and manually select input source.
Selection is done via json interface or hyperion-remote.
To select e.g. priority channel 900 call:
`hyperion-remote --sourceSelect 900`
This will disable automatic/priorized source selection. To reactivate auto select call:
`hyperion-remote --sourceAutoSelect`
You can only select prio channels that are active.
The serverinfo json command adds new value "visible" to every priority. That is needed to determine what is currently visible.
```
"priorities" : [
{
"active" : true,
"duration_ms" : 184,
"owner" : "X11 Grabber",
"priority" : 900,
"visible" : true
},
{ …
```
> Manual input source select via json

- include/hyperion/Hyperion.h
- include/utils/Components.h
- libsrc/hyperion/CMakeLists.txt
- libsrc/hyperion/Hyperion.cpp
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/jsonserver/JsonClientConnection.h
- libsrc/jsonserver/JsonSchemas.qrc
- libsrc/jsonserver/schema/schema-componentstate.json
- libsrc/jsonserver/schema/schema.json
- src/hyperion-remote/JsonConnection.cpp
- src/hyperion-remote/JsonConnection.h
- src/hyperion-remote/hyperion-remote.cpp
With this code we are able to enable or disable components during runtime.
Available Components are:
SMOOTHING, BLACKBORDER, KODICHECKER, FORWARDER, UDPLISTENER, BOBLIGHT_SERVER, GRABBER
Example:
To enable the Component "Kodi Video Checker" during runtime send the JSON Object:
{"command":"componentstate","componentstate":{"component":"KODICHECKER","state":true}}
or use
hyperion-remote --enable "KODICHECKER"
To disable the Component "KodiVideoChecker" during runtime send the JSON Object:
{"command":"componentstate","componentstate":{"component":"KODICHECKER","state":false}}
or use
hyperion-remote --disable "KODICHECKER"
no
#21 …
> Update Json Interface (Enable/Disable components during runtime)

- libsrc/leddevice/LedDeviceHyperionUsbasp.cpp
The usbasp device driver had data type errors in the log calls causing it to segfault with logging enabled.
nope
> Fix segmentation fault in usbasp led driver

- assets/webconfig/select/index.html
- assets/webconfig/select/starter-template.css
- config/hyperion.config.json.commented
- config/hyperion.config.json.default
- include/hyperion/PriorityMuxer.h
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/PriorityMuxer.cpp
- libsrc/hyperion/hyperion.schema.json
- libsrc/jsonserver/JsonClientConnection.cpp
- src/hyperion-remote/hyperion-remote.cpp
- src/hyperiond/hyperiond.cpp
- src/hyperiond/hyperiond.h
- src/hyperiond/main.cpp
add --sourceOff to hyperion-remote - this will select "off" source and set all leds to black
to switch leds back to "on" use --sourceAutoSelect or select a specific source --sourceSelect
-> this is useful for the 24/7 people that complain that their leds blink when nothing is on. (because we send actively black color, leds should stay off)
some tiny refactoring of new json stuff
make schema checker not so strict, do not require values that have defaults (not finished yet)
-> the goal should be that we can start with an empty config and hyperion runs (with default values)
-> this is neccessary for inital setup where the user hasn't configured anything
initialEffect config:
effect is always an array, regardless if it is a color or an effect name …
> sourceOff feature + small json refactoring

- .travis.yml
It doesn't really do all that much but it does speed up Travis builds slightly by enabling ccache and the brew download cache for the OS X build.
It's still slow, but less so :)
> Added some Travis caching

- include/grabber/DispmanxWrapper.h
- include/grabber/V4L2Grabber.h
- include/grabber/V4L2Wrapper.h
- libsrc/grabber/v4l2/V4L2Grabber.cpp
- libsrc/grabber/v4l2/V4L2Wrapper.cpp
- libsrc/hyperion/GrabberWrapper.cpp
- src/hyperiond/hyperiond.cpp
v4l errors won't lead to crash hyperiond (exceptions are catched)
v4l auto device mode with better log messages
createV4l in hyperiond.cpp refactored, now v4l is always available as long as it is compiled in
to test the exception thing, start hyperiond with v4l, then pull usb plug of grabber, now v4l should be switched off. Currently it is not possible to reenable it via hyperion-remote/json. This will be possible in future ...
additional:
fix compile of dispmanx (bug was introduced with latest grabber rework)
> v4l grabber wont crash hyperiond anymore

- libsrc/leddevice/LedDeviceFactory.cpp
- libsrc/leddevice/LedDeviceSk6812SPI.cpp
- libsrc/leddevice/LedDeviceSk6812SPI.h
- libsrc/leddevice/LedDeviceWs2801.cpp
- libsrc/leddevice/LedDeviceWs2801.h
- libsrc/leddevice/LedDeviceWs2812SPI.cpp
- libsrc/leddevice/LedDeviceWs2812SPI.h
- libsrc/leddevice/LedSpiDevice.cpp
- libsrc/leddevice/LedSpiDevice.h
- test/TestSpi.cpp
Added "invert" and "spimode" options to ws2801, ws2812spi and sk6812spi devices
This adds the option to invert the SPI data line and the SPI clock line.
This is nice if you want to use a level shifter that inverts the signal(s)
"rate"       : 1000000,
"spimode"    : 0,
"invert"     : true,
"colorOrder" : "grb"
#101
> Added "invert" and "spimode" options to ws2801, ws2812spi and sk6812spi devices

- config/hyperion.config.json.commented
- config/hyperion.config.json.default
- include/utils/jsonschema/JsonFactory.h
- include/utils/jsonschema/JsonSchemaChecker.h
- libsrc/hyperion/hyperion.schema.json
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/jsonserver/JsonClientConnection.h
- libsrc/jsonserver/JsonSchemas.qrc
- libsrc/jsonserver/schema/schema-configset.json
- libsrc/jsonserver/schema/schema.json
- libsrc/utils/jsonschema/JsonSchemaChecker.cpp
- src/hyperion-remote/JsonConnection.cpp
- src/hyperion-remote/JsonConnection.h
- src/hyperion-remote/hyperion-remote.cpp
Wie der Titel schon vermuten lässt, lassen sich mit dieser Funktion, einzelne, mehrere, oder gleich alle Werte in die hyperion config schreiben. 
Der JSON Befehl ist wie folgt aufgebaut:
{"command" : "configset", "configset" : { "logger" : {"level" : "debug"} } , "create" : false}
Der Schlüssel command enthält den eigentlichen Befehl "configset".
Der Schlüssel configset beinhaltet den zu schreibenden JSON String.
Und der Schlüssel create gibt an, ob die nicht vorhandenen Werte in der zu beschreibenden config erstellt werden sollen oder nicht. Der Standard ist false.
Im obigen Beispiel werden nur die vorhanden Werte aktualisiert ,wenn der logger schon in der config vorhanden ist.
Hyperion-remote unterstützt natürlich auch diesen Befehl. Dieser …
> JSON RPC Writer (configSet)

- libsrc/hyperion/hyperion.schema.json
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/jsonserver/JsonClientConnection.h
- libsrc/jsonserver/schema/schema-adjustment.json
- libsrc/jsonserver/schema/schema-clear.json
- libsrc/jsonserver/schema/schema-clearall.json
- libsrc/jsonserver/schema/schema-color.json
- libsrc/jsonserver/schema/schema-componentstate.json
- libsrc/jsonserver/schema/schema-config.json
- libsrc/jsonserver/schema/schema-correction.json
- libsrc/jsonserver/schema/schema-effect.json
- libsrc/jsonserver/schema/schema-image.json
- libsrc/jsonserver/schema/schema-serverinfo.json
- libsrc/jsonserver/schema/schema-sourceselect.json
- libsrc/jsonserver/schema/schema-temperature.json
- libsrc/jsonserver/schema/schema-transform.json
- libsrc/jsonserver/schema/schema.json
- in json reply the command is written again, to better identify it.
- also added a transaction number (tan). This is a user defined number to track exactly every request-reply relation (default is 0 if not used)
examples:
```
Command: {"command":"clearall"}
Reply: {"command":"clearall","success":true,"tan":0}
Command: {"command":"clearall","tan",111}
Reply: {"command":"clearall","success":true,"tan":111}
```
additional:
- fix hyperion.schema.json (wrong format and missing "rgb" in colorOrder enum)
> extend json api to better track request-reply relations

- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/jsonserver/schema/schema-config.json
- src/hyperion-remote/JsonConnection.cpp
- src/hyperion-remote/JsonConnection.h
- src/hyperion-remote/hyperion-remote.cpp
Update:
Die "overwrite" Option im Zusammenhang mit setConfig ermöglicht jetzt das komplette überschreiben der Hyperion config Datei. Bis jetzt war es nur möglich, die config zu aktualisieren oder mit der Zusatzoption  "create" neue Schlüssel hinzu zu fügen, wenn sich diese noch nicht in der config befunden haben.
Kleines Beispiel ausgehen von der Standard Konfigurationsdatei:
Senden wir den unten stehenden JSON String an den Hyperionserver, versetzen wir den logger in den Debug modus. Dies funktioniert nur, wenn sich der logger schon in der config befindet. Sollte er nicht vorhanden sein, müssten wir die option "create" auf true setzen. Dadurch wird der Schlüssel in die aktuelle config hinzugefügt. …
> Update and fix JSON writer

- libsrc/leddevice/LedSpiDevice.cpp
- libsrc/leddevice/LedUdpDevice.cpp
Fix throw error so it correctly fails on invalid output hostnames
Fixed broken default /dev/spidev0.0 string
UDP devices now use "host" and "port" rather than "output"
All devices that use the lowlevel UDP driver need a new config:
OLD:
```
"device" :
{
"output"     : "10.0.0.60:5568",
}
```
NEW:
```
"device" :
{
"host"     : "10.0.0.60",
"port"     : 5568,
}
```
> Fix throw error in udp, fix default SPI device

- libsrc/leddevice/LedDeviceUdpE131.cpp
- libsrc/leddevice/LedDeviceUdpE131.h
- source-name defaults to "hyperion on <hostname>"
- cid defautls to randomly generated on each startup
- if cid is unparsable, falls back to  {00000000-0000-0000-0000-000000000000}
```
"device" :
{
"name"       : "DMX_e131",
"type"       : "e131",
"universe"   : 1,
"cid" : "{7204b83c-efb5-4b23-b2d0-35939d561061}",
"source-name": "This is my custom e1.31 source",
"host"       : "239.255.0.1",
"port"       : 5568,
"colorOrder" : "rgb"
},
```
> Added source-name and cid to e1.31 driver.

- libsrc/leddevice/ProviderSpi.cpp
If you have more leds configured than the SPI buffer can support you now get this:
[HYPERIOND LedDevice] <DEBUG> <ProviderSpi.cpp:92:writeBytes()> SPI failed to write. errno: 90, Message too long
nope
> Added debug logging to ProviderSpi.cpp on writes.

- config/hyperion.config.json.commented
- config/hyperion.config.json.default
- include/hyperion/GrabberWrapper.h
- include/utils/Components.h
- libsrc/grabber/v4l2/V4L2Grabber.cpp
- libsrc/grabber/v4l2/V4L2Wrapper.cpp
- libsrc/hyperion/GrabberWrapper.cpp
- libsrc/hyperion/hyperion.schema.json
- libsrc/jsonserver/schema/schema-componentstate.json
- src/hyperion-remote/hyperion-remote.cpp
- src/hyperiond/hyperiond.cpp
- src/hyperiond/hyperiond.h
now it is possible to use multiple v4l devices.
Attention:
Not all v4l devices are compat with that or must be attaches to different usb controller.
see: http://superuser.com/questions/431759/using-multiple-usb-webcams-in-linux#433237
additional:
split component GRABBER and V4L (#204)
yes, v4l-grabber is now an array. You can add multiple device blocks ... see default config
my config:
```
"grabber-v4l2" : 
[
{
"enable" : true,
"device" : "usbtv",
"input" : 0,
"standard" : "PAL",
"width" : -1,
"height" : -1,
"frameDecimation" : 2,
"sizeDecimation" : 8,
"priority" : 890,
"mode" : "2D",
"cropLeft" : 15,
"cropRight" : 12,
"cropTop" : 10,
"cropBottom" : 10, …
```
> multiple v4l devices.

- libsrc/leddevice/LedDeviceSk6812SPI.cpp
- libsrc/leddevice/LedDeviceWs2812SPI.cpp
- libsrc/leddevice/LedDeviceWs2812SPI.h
- libsrc/leddevice/ProviderSpi.cpp
- libsrc/leddevice/schemas/schema-sk6812rgbw-spi.json
- libsrc/leddevice/schemas/schema-ws2812spi.json
now sets the default baud_rate speed to 3000000 if omitted.
Previously it used the ProviderSPI default which was 1000000 and guaranteed not to work
Added warnings if the SPI baud rate is likely out of range
Added some debug statements to ProviderSpi
nope
#216
> Ws2812spi and sk6812rgbw have wrong default rate

- libsrc/hyperion/CMakeLists.txt
- src/hyperion-aml/CMakeLists.txt
- src/hyperion-dispmanx/CMakeLists.txt
- src/hyperion-framebuffer/CMakeLists.txt
- src/hyperion-osx/CMakeLists.txt
- src/hyperion-remote/CMakeLists.txt
- src/hyperion-v4l2/CMakeLists.txt
- src/hyperion-x11/CMakeLists.txt
- test/CMakeLists.txt
resolve cyclic dependencies between hyperion modules. Now we can compile as shared libs (again).
This is needed preparation for dynamicly load (dlopen) grabbers or other components.
```
cd build
cmake -DBUILD_SHARED_LIBS=ON ..
make -j$(nproc)
export LD_LIBRARY_PATH="lib:$LD_LIBRARY_PATH"
bin/hyperiond --debug path_to_my_config.json
```
generated libs (for platform x86-dev):
```
libamlogic-grabber.so
libblackborder.so
libboblightserver.so
libbonjour.so
libcommandline.so
libeffectengine.so
libframebuffer-grabber.so
libhidapi-libusb.so
libhyperion.so
libhyperion-utils.so
libjsoncpp.so
libjsonserver.so
libkodivideochecker.so
libleddevice.so
libprotobuf-lite.so
libprotobuf.so
libprotoc_lib.so
libprotoserver.so
libtinkerforge.so
libudplistener.so …
```
> make shared libs work again

- assets/webconfig/css/hyperion.css
- assets/webconfig/index.html
- assets/webconfig/js/content_index.js
- assets/webconfig/js/content_leds.js
- assets/webconfig/js/ui_utils.js
- config/hyperion.config.json.default
- include/hyperion/Hyperion.h
- include/webconfig/WebConfig.h
- libsrc/effectengine/CMakeLists.txt
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/hyperion.schema.json
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/webconfig/CMakeLists.txt
- libsrc/webconfig/StaticFileServing.cpp
- libsrc/webconfig/WebConfig.cpp
- libsrc/webconfig/WebConfig.qrc.in
optional embedded webui. If document_root in config is set and valid, files taken from there, otherwise compiled in files are taken.
For customer release it is great, because we always have a webui (as long as hyperiond is started).
Webfiles are included in libwebconfig.so separated from hyperiond.
Currently we compile a static binary and of course for now files are embedded in hyperiond directly.
Currently filesize is increase about 2MB -> mean 3.6MB total for a striped binary
Hyperion and webui now have a detection if config file was altered during runtime of hyperiond. We need this detection for reloading new config
**Attention webui developers:** set document_root in config (as before), otherwise you won't have fun ;-)
**2.** If this …
> embedded webui + config modification detection

- config/hyperion.config.json.commented
Example config json is missing a comma making it invalid json
> Example config json is missing a comma

- libsrc/leddevice/ProviderRs232.cpp
- libsrc/leddevice/ProviderRs232.h
In all docs it is stated out, that async usage of qserialport is recommended. now providerRS232 is adapted to that. I added the possibility for reading from serialport (but nothing is done with that data atm), also Logging output and error handling is improved.
Under some circumstances the rs232 provider is able to reconnect on connection loss (e.g. reset of arduino (testet with leo, reset works, reconnect usb plug didn't due to board/firmware behaviour))
> switch rs232 provider to async transfer

- libsrc/hyperion/Hyperion.cpp
... fix input selection wont work when color is set
test:
- start hyperion
- open webui -> remote controll
- set a color
- try to set a specific input source
-> current: led color stays always
-> fixed: led colors are set according selected input source
> fix input selection wont work when color is set

- libsrc/hyperion/LinearColorSmoothing.cpp
- libsrc/hyperion/LinearColorSmoothing.h
Increase color change for small RGB differences.
k*difference could be rounded to 0 for small k or small differences, which resulted in no color update.
see [forum post](https://hyperion-project.org/threads/smoothing-problem.271/page-2#post-3284)
>  Smoothing Fix

- include/hyperion/Hyperion.h
- libsrc/hyperion/Hyperion.cpp
- libsrc/jsonserver/JsonClientConnection.cpp
..  now devices closed before restart.
Before that it wasn't possible to restart hyperion via json/webui with serial device (adalight), because serialport was left open after exit the prior hyperion instance.
> fix restart of hyperion. 

- libsrc/leddevice/LedDeviceAtmoOrb.cpp
QHostAddress::Any no longer works with used Qt version, this resolves it by changing it so that it binds to Any IPv4 address.
> Fixed QHostAddress address binding for AtmoOrb

- include/effectengine/EffectDefinition.h
- libsrc/effectengine/EffectEngine.cpp
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/jsonserver/JsonClientConnection.h
- libsrc/jsonserver/JsonSchemas.qrc
- libsrc/jsonserver/schema/schema-delete-effect.json
- libsrc/jsonserver/schema/schema.json
- src/hyperion-remote/JsonConnection.cpp
- src/hyperion-remote/JsonConnection.h
- src/hyperion-remote/hyperion-remote.cpp
In german.
Wie der Titel schon vermuten lässt, kann man **benutzerdefinierte** Effektkonfigurationen löschen.
Das Wort "benutzerdefinierte" habe ich Fett geschrieben, aus dem Grund, es sind nur die externen und NICHT die internen Effektkonfigurationen gemeint.
Die Verwendung ist einfach. Haben wir z.b. einen neuen Effekt mit dem Namen "dream" erstellt, löschen wir diesen folgendermaßen. 
hyperion-remote:
./hyperion-remote --deleteEffect "dream"
JSON RPC:
{"command":"delete-effect","name":"dream"}
EDIT: Ach ja, fast vergessen. Die "effects" Serverinfo von Hyperion enthält jetzt auch den Dateipfad der Effektkonfigurationen.
nein
> Delete custom created effect configurations with JSON RPC

- include/utils/Logger.h
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/jsonserver/JsonClientConnection.h
- libsrc/leddevice/ProviderRs232.cpp
- libsrc/utils/CMakeLists.txt
- libsrc/utils/Logger.cpp
- libsrc/utils/Profiler.cpp
implement a in memory global log buffer. this can be used for e.g. webinterface to retrieve last log messages
call:
`QVector<Logger::T_LOG_MESSAGE>* logMessages = Logger::getGlobalLogMessageBuffer();`
to retrieve the messages. (logger.h should provide needed info about the message struct)
> global logbuffer

- libsrc/leddevice/LedDeviceWs2801.cpp
- libsrc/leddevice/schemas/schema-ws2801.json
Added latchtime web configuration for ws2801 device.
Fixed default to be 500000ns
not directly - if omitted the defatul is now 500,000ns rather than zero
> Added latchtime web configuration for ws2801 device.

- CompileHowto.md
The commant 
`cd git clone --recursive https://github.com/hyperion-project/hyperion.ng.git hyperion`
should be
`git clone --recursive https://github.com/hyperion-project/hyperion.ng.git hyperion`
> Fix wrong command in CompileHowto

- CompileHowto.md
Me and penfold42 compiled it on Windows 10 Bash window and it compiled and ran, so I added it to the compile howto
> Update CompileHowto.md to say that Ubuntu instructions apply to Win10 Linux Subsystem

- config/hyperion.config.json.commented
- config/hyperion.config.json.default
- include/grabber/V4L2Grabber.h
- include/grabber/V4L2Wrapper.h
- include/utils/ColorRgb.h
- libsrc/grabber/v4l2/V4L2Grabber.cpp
- libsrc/grabber/v4l2/V4L2Wrapper.cpp
- libsrc/hyperion/hyperion.schema.json
- src/hyperion-v4l2/ScreenshotHandler.cpp
- src/hyperion-v4l2/ScreenshotHandler.h
- src/hyperion-v4l2/hyperion-v4l2.cpp
- src/hyperiond/hyperiond.cpp
some HDMI2AV generates rainbow patterns when no signal is detected. This is not detectable with current signal detection mechanism.
More details here:
https://hyperion-project.org/threads/v4l2-add-shutdown-detection.146/
https://github.com/hyperion-project/hyperion/issues/92
I tested with this picture
to activate add following lines to grabberv4l section in config:
```
"signalDetectionVerticalOffsetMin"   : 0.25,
"signalDetectionHorizontalOffsetMin" : 0.25,
"signalDetectionVerticalOffsetMax"   : 0.75,
"signalDetectionHorizontalOffsetMax" : 0.75
```
This describes the area where to analyze the signal threshold. This values in particular are the current state. The values for the rainbow pic shown above are `0.47 0.2 0.49 0.8` - only the left blue …
> Kill "Rainbow lights" when v4l grabber has no signal

- config/hyperion.config.json.commented
- config/hyperion.config.json.default
- include/hyperion/Hyperion.h
- include/hyperion/ImageProcessor.h
- include/hyperion/ImageProcessorFactory.h
- include/hyperion/ImageToLedsMap.h
- libsrc/hyperion/CMakeLists.txt
- libsrc/hyperion/GrabberWrapper.cpp
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/ImageProcessor.cpp
- libsrc/hyperion/ImageProcessorFactory.cpp
- libsrc/hyperion/ImageToLedsMap.cpp
- libsrc/hyperion/hyperion.schema.json
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/jsonserver/JsonClientConnection.h
- libsrc/jsonserver/JsonSchemas.qrc
- libsrc/jsonserver/schema/schema.json
- src/hyperion-remote/JsonConnection.cpp
- src/hyperion-remote/JsonConnection.h
- src/hyperion-remote/hyperion-remote.cpp
you can switch between multicolor (all leds could have different colors) und unicolor mode.
unicolor means all leds have sa same color. The color is calculated from the average of the whole(!) image.
This method is not the best, because it gets sometimes to dark, but it's a start. This methode is very cool when you watch pictures.
In general we have now a methode to implement other image to led mapping algorithms.
usage:
use it via hyperion-remote or json interface with you own application:
unicolor mode
```
bin/hyperion-remote -M unicolor_mean --print
hyperion-remote:
Version   : 2.0.0 (unicolor (redpanther-90f27a1/cbec2f4-1482083992))
build time: Dec 18 2016 19:02:32
Connected to: "localhost:19444" 
Command: {"command": …
```
> adjustable image2led mode for grabbers

- libsrc/leddevice/ProviderSpi.cpp
the SPI write ioctl returns # bytes written, not 0....
(unless of course you have 0 leds!)
> Fix latchtime logic - it was always ignored

- assets/webconfig/errorpages/403.html
- assets/webconfig/errorpages/404.html
- assets/webconfig/errorpages/405.html
- assets/webconfig/errorpages/500.html
- assets/webconfig/errorpages/footer.html
- assets/webconfig/errorpages/header.html
- assets/webconfig/index.html
- assets/webconfig/server_scripts/demo.sh
- include/utils/Process.h
- libsrc/utils/Process.cpp
- libsrc/webconfig/CgiHandler.cpp
- libsrc/webconfig/CgiHandler.h
- libsrc/webconfig/StaticFileServing.cpp
- libsrc/webconfig/StaticFileServing.h
- src/hyperiond/main.cpp
add http error pages ... design is more a placebo ;-)
> add http error pages 

- effects/pacman.json
- effects/pacman.py
> add Pac-Man effect

- CompileHowto.md
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/webconfig/CgiHandler.cpp
should solve #404 
currently missing: a proper message in web ui when config write fails. To test use led layout edit box and write valid json, but invalid content (e.g. xhscan instead of hscan)
> check config when writing

- libsrc/hyperion/PriorityMuxer.cpp
prio 254/255 are used by system for background stuff. This shouldn't be affected by clearall
> clearall don't remove prio 254/255 

- effects/light-clock.py
- effects/rainbow-swirl.py
- libsrc/effectengine/Effect.cpp
- libsrc/effectengine/Effect.h
- add func for setting minimum size of effect buffer image. This must be done asap in the effect
```
hyperion.imageMinSize(64,64)
```
- add posibility to save a image to memory list. Func returns the index  of the saved picture. You can pre draw your frames and then show just the images in the loop.
```
imgList = []
hyperion.imageSolidFill(255,0,0)
imgList.append( hyperion.imageSave() )
hyperion.imageSolidFill(0,255,0)
imgList.append( hyperion.imageSave() )
hyperion.imageSolidFill(0,0,255)
imgList.append( hyperion.imageSave() )
while not hyperion.abort():
for img in imgList:
hyperion.imageShow(img)
time.sleep(1)
if hyperion.abort(): break
```
**3.** Reference an …
> extend image based effect funcs

- assets/webconfig/i18n/de.json
- assets/webconfig/i18n/en.json
- assets/webconfig/i18n/es.json
- libsrc/leddevice/LedDeviceHyperionUsbasp.cpp
- libsrc/leddevice/schemas/schema-hyperionusbasp.json
HyperionUsbAsp supports both ws2801 and ws2812 led strips
Re-add this option to the schema
```
"device": {
"colorOrder": "grb",
"latchTime": 10,
"ledType": "ws2812",
"rewriteTime": 5000,
"type": "hyperionusbasp"
},
```
> HyperionUsbAsp ws2812 broken

- libsrc/utils/RgbTransform.cpp
This fixes #493 and is also present on the latest beta rework branch.
Nothing more to be said.
> none
#493
> RGBTransform fix gamma adjustment of green, blue always taking red value

- libsrc/leddevice/dev_net/LedDevicePhilipsHue.cpp
Hue RGB Color Conversion for Brightness is wrong! - use RGB to HSV instead of XYZ Space! 
For correct use, reset brightnessFactor back to 1.0 in config! - It was just a Workaround, not the Solution!
Fixed wrong ColorGamut A/B/C Values + Added New Lamp/Light Models: LCT015, LCT016, LCT024
> Fixes PhilipsHue Brightness, ColorGamut + new Lights

- dependencies/CMakeLists.txt
- include/bonjour/bonjourservicebrowser.h
- include/bonjour/bonjourserviceregister.h
- include/bonjour/bonjourserviceresolver.h
- src/hyperion-aml/CMakeLists.txt
- src/hyperion-framebuffer/CMakeLists.txt
- src/hyperion-remote/CMakeLists.txt
- src/hyperion-v4l2/CMakeLists.txt
- src/hyperiond/CMakeLists.txt
added missing librarys and inludes by amlogic compiler flag
> fix amlogic compile

- include/grabber/V4L2Wrapper.h
- libsrc/grabber/v4l2/V4L2Grabber.cpp
- libsrc/grabber/v4l2/V4L2Wrapper.cpp
- src/hyperiond/hyperiond.cpp
re-enable the "enable" config flag for V4L2 grabber
V4L2 would start everytime, also if enabled == false
> fix V4L2 grabber enable

- CompileHowto.md
I have problem when execute "make -j $(nproc)", so the user Akriss from Hyperion Forum oriented me to execute the command "sudo apt-get install rbp-userland-dev-osmc" instead of "sudo apt-get install libraspberrypi-dev". Then I could execute "make -j $(nproc)".
So I added a sub-section called "if you have a problem when execute.." with the new command. Not sure if the title is good, feel free to change.
Thanks a lot
> New command

- libsrc/hyperion/LinearColorSmoothing.cpp
- libsrc/leddevice/LedDeviceWrapper.cpp
- src/hyperiond/main.cpp
Add SIGUSR1 and SIGUSR2 signals to disable/enable the LEDs for suspend mode or more.
Fixed missing enable on LedDeviceWrapper constructor.
None
The LEDs remain on if the control box goes offline without setting the LEDs to off.
> Add SIGUSR1 and SIGUSR2 signals to disable/enable the LEDs

- libsrc/leddevice/LedDeviceWrapper.cpp
In case a running hyperiond is "killed", a core-dump is created due to the fact that a QThread for LEDDevice is still running.
Add QThread->wait() ensuring QThread completes before further destructors are called.
> Fix LEDDeviceWrapper coredump when killing hyperiond

- assets/webconfig/js/wizard.js
- libsrc/leddevice/dev_net/LedDevicePhilipsHue.cpp
- Fixing PhilipsHue Wizard: The Wizard had trouble updating the values to the JSONEditor. Besides of that the manual IP entry in the wizard was broken (is needed when auto lookup fails). The auto lookup page from Philips moved to an other URL. Old URL is officially not available anymore since 1st July 2019. See this post: https://developers.meethue.com/news/ (Bridge Discovery Endpoint Change)
- Fixes #545 I have tested this on my Philips Hue Setup as well
> Fixing PhilipsHue wizard, Fixing issue #545

- bin/create_all_releases.sh
- bin/create_release.sh
- libsrc/leddevice/LedDevice.cpp
Reimplement to be able to switch on/off devices via the LED Device UI button.
Before the change devices will only be switched off, but not on again.
This is mainly relevant for devices which override the LedDevice switchOn/Off methods to do API calls
rather than have a black output stream.
> Allow to switch on LED device, if currently disabled

- cmake/debian/postinst
- cmake/debian/preinst
- cmake/debian/prerm
- cmake/rpm/postinst
- cmake/rpm/preinst
- cmake/rpm/prerm
Fixes an issue where multiple users returned from `who` causes grep to be greedy and return a regex matched string containing all users, not the first user as intended.
This caused the package installation on Raspbian to create an incorrect service name which could not be started as there was a mismatch in user vs expected user.
As discussed with @Paulchen-Panther [HERE](https://hyperion-project.org/threads/installing-hyperion-ng.3491/page-3#post-15695)
Fresh install of Raspbian Stretch, calling `who` from the terminal returns two users. Doing the same on an SSH session returns 3:
```
pi@raspberrypi:~ $ who
pi       tty1         2019-08-07 17:38
pi       tty7         2019-08-07 17:39 (:0)
pi       pts/0        2019-08-07 17:41 (10.26.25.176)
```
After regexp:
```
pi@raspberrypi:~ $ who | …
```
> Debian post-inst script fails to correctly create system service when multiple users are present

- libsrc/leddevice/dev_rpi_pwm/LedDeviceWS281x.cpp
When initializing LedDeviceWS281x `_led_string` field (ws2811_t) was not filled with zeros (thus was filled with garbage) and that prevented proper initialization of it's `gamma` pointer, accessing which causes a SIGSEGV.
Added initialization of `_led_string` field with zeros which results in proper memory allocation for `gamma`.
Tested locally.
Fixes #564
> Fix RPI WS281x LED device initialization

- libsrc/python/PythonInit.cpp
- src/hyperiond/main.cpp
- Refactored exception handling in main
Exceptions thrown by HyperionDaemon did not result in stopping the application, but had the qt application still running. Exception thrown for rootPaths were even not caught, as thrown outside a try block. In case hyperion should run without daemon ,come back to me.
- During my testing to ship libraries with the app, I identified that hyperiond starts even, if Python failed to initialise. Added an exception, if Python failed initialisation.
> Refactored Exceptions in main & PythonInit

- libsrc/grabber/amlogic/IonBuffer.h
https://discourse.coreelec.org/t/slow-down-of-hyperion-ng/341/356?u=portisch
none
warning: throw will always call terminate
> fix warning: throw will always call terminate

- libsrc/api/JSONRPC_schema/schema-image.json
- libsrc/api/JsonAPI.cpp
The origin parameter when setting an image was set to required - unlike when setting a color or an effect. 
This change makes the origin parameter optional and sets the min and max length of the value to be the same as in color and effect.
no
none
> Make origin in schema-image optional

- assets/webconfig/content/remote.html
- assets/webconfig/i18n/de.json
- assets/webconfig/i18n/en.json
- assets/webconfig/index.html
- assets/webconfig/js/content_remote.js
- assets/webconfig/js/hyperion.js
- assets/webconfig/js/streamer.js
- assets/webconfig/js/ui_utils.js
- libsrc/api/JSONRPC_schema/schema-image.json
- libsrc/api/JsonAPI.cpp
- libsrc/hyperion/PriorityMuxer.cpp
This PR adds a new image sending feature to the webui and extends the api accordingly. In javascript the processing of images is horrible slow (without WASM), so the solution is at the API side with out-of-the-box power of Qt.
- The image cmd accepts now a raw image that is encoded with base64. Supported are all image formats that qt supports (that are enough)
- There is no real size limit. It will be automatically scaled down to max 2000px width or height while maintain aspect ratio
- It's possible to scale down through a new "scale" property if developer wants that.
- Test were successful until 3MP pictures, 4k+ seems to close the websocket on browser side, so 2k is a decent value
- Note: Bootstrap 3 doesn't support file input "adjustment", for better visual style we should add a css …
> Feat: Add image sender to webui + Browser screen capture

- assets/webconfig/content/about.html
- assets/webconfig/i18n/de.json
- assets/webconfig/i18n/en.json
- assets/webconfig/index.html
- assets/webconfig/js/content_colors.js
- assets/webconfig/js/ui_utils.js
- assets/webconfig/js/wizard.js
- config/hyperion.config.json.commented
- config/hyperion.config.json.default
- libsrc/hyperion/schema/schema-network.json
This PR introduces the changes mentioned here: https://github.com/hyperion-project/hyperion.ng/pull/592#issuecomment-521255373
- A notification of the current instance is shown when the selected instance is not the default one.
- The current instance is stored to a local storage.
- After a page refresh the last selected instance stored in local storage is selected (e.g. fixes wizard instance switch bug)
- Addes a new checkbox for Whitelisting internet IPs for API. Should be clearer now. 
"network" :
{
"internetAccessAPI" : false,
**"restirctedInternetAccessAPI" : false,**
"ipWhitelist" : [],
"apiAuth" : true,
"localApiAuth" : false
},
**3.** Reference an issue …
> WebUi: New Internet API logic, correct switch to last instance after refresh, current instance notification

- assets/webconfig/content/conf_leds.html
- assets/webconfig/i18n/de.json
- assets/webconfig/i18n/en.json
- assets/webconfig/js/content_dashboard.js
- assets/webconfig/js/content_index.js
- assets/webconfig/js/content_leds.js
- assets/webconfig/js/ui_utils.js
- assets/webconfig/js/wizard.js
- libsrc/api/JsonAPI.cpp
- libsrc/hyperion/Hyperion.cpp
- FIx: general colorOrder just worked after complete restart
-  Fix: ledDevice should be shown properly on webui after saving
- Fix: syntax error in wizard.js
https://github.com/hyperion-project/hyperion.ng/issues/619
> Bugfixes [TBC]

- assets/webconfig/i18n/cs.json
- assets/webconfig/i18n/de.json
- assets/webconfig/i18n/en.json
- assets/webconfig/i18n/es.json
- assets/webconfig/i18n/it.json
- libsrc/leddevice/schemas/schema-ws281x.json
The ws281x device has a PWM channel [option](https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/leddevice/dev_rpi_pwm/LedDeviceWS281x.cpp#L33) which was missing from the web interface.
> Add PWM channel option for ws281x device in web interface

- libsrc/leddevice/dev_hid/LedDeviceLightpack.cpp
This fixes a segmentation fault in debug mode with a Lightpack device.
Without this change:
```
./bin/hyperiond  -d                                                                                                                                                                        
[hyperiond MAIN] <INFO> Set user data path to '/home/patrick/.hyperion'
...
[hyperiond LEDDEVICE] <DEBUG> <LedDeviceLightpack.cpp:97:open()> USB context initialized
[hyperiond LEDDEVICE] <INFO> Found a lightpack device. Retrieving more information...
[hyperiond LEDDEVICE] <DEBUG> <LedDeviceLightpack.cpp:168:testAndOpen()> Lightpack device found: bus=3 address=116 serial=9523030323**********
[hyperiond LEDDEVICE] <INFO> Lightpack device successfully opened …
```
> Fix a segfault in debug mode with lightpack

- libsrc/leddevice/dev_serial/ProviderRs232.cpp
- libsrc/leddevice/dev_serial/ProviderRs232.h
Add a timeout on asynchronous write. Sometimes it happen that the `.write` is successful but no bytes are written at all. This will be  catched by the timeout timer like the QSerialPort example is showing.
Also the handling of written bytes in function `bytesWritten` got modified as only one single transfer can be handled in one shot on the asynchronous connection.
none
See 1.
> Add RS232 timeout for asynchronous connection

- assets/webconfig/js/content_leds.js
- config/hyperion.config.json.default
- libsrc/hyperion/schema/schema-ledConfig.json
**Summary**
Save and Restore Led Matrix Layout
including the migration form old to new data structure.
**The PR fulfils these requirements:**
Addresses #669
> Led Matrix Layout - Save/Restore (#669)

- libsrc/leddevice/LedDevice.cpp
- libsrc/leddevice/dev_net/LedDeviceNanoleaf.cpp
- libsrc/leddevice/dev_net/ProviderUdp.cpp
**Summary**
Fix Nanoleaf - UDP Network initialisation was missing
LedDevice - Suppress debug output, if device is not ready
Fix addresses issue reported in forum:
https://hyperion-project.org/threads/segmentation-fault-hyperion-ng-auf-raspbian-pi3.10432/
> Fix Nanoleaf - Udp Network init was missing

- libsrc/flatbufserver/FlatBufferClient.cpp
- libsrc/flatbufserver/FlatBufferConnection.cpp
- libsrc/hyperion/MessageForwarder.cpp
**Summary**
Flatbuffer forwarder was not working correctly, and crashing Hyperion.
The issue turned out to be caused by incorrectly assuming that the socket buffer would only contain one header and one flatbuffer message, resulting in a race condition which could cause the flatbuffer library to fail to verify the corrupted buffer it was passed. 
Upon failing to verify the buffer, the client attempts to sendErrorReply, which due to the same issue on the server causes Hyperion to crash with "Unable to parse reply".
Additionally, after fixing this issue, I discovered there was a memory leak caused by sendMessage on the server only conditionally clearing the flatbuffer builder. If a client was not connected, this caused the builder to grow without bound until it causes a segfault/badalloc. I …
> Fixes for multiple memory leaks and segfault issues in Flatbuffer Forwarder

- .github/workflows/pull-request.yml
**Summary**
Now our GitHub app should ensure that the link to GitHub Actions is integrated into PR.
Unfortunately I have not yet figured out how to extract the "run_id" from the current GitHub Actions workflow under Probot in order to provide a direct link to the artifacts. Should anyone know more about this. Please report.
To avoid wasting your time, it's best to open a **feature request issue** first …
> Removed PR comment job from Github Actions 

- libsrc/ssdp/SSDPHandler.cpp
- libsrc/webserver/WebServer.cpp
**Summary**
SSDP Server should at least answer on `ssdp:all` with `urn:hyperion-project.org:device:basic:1` instead of `ssdp:all`.
> fix(ssdp): ssdp:all provide better feedback

- libsrc/hyperion/ImageProcessor.cpp
**Summary**
- Fix Coredump, in case (X11) Grabber was excluded from compile.
A Led-settings update triggers setLedString where _imageToLeds has not been initialised yet.
Call _imageToLeds->width(); results in a coredump.
- Fix Memory Leaks,as object _imageToLeds is not properly deleted
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on …
> Fix Memoryleaks & Coredump, if no Grabber compiled

- assets/webconfig/i18n/de.json
- assets/webconfig/i18n/en.json
- assets/webconfig/js/wizard.js
- include/leddevice/LedDevice.h
- libsrc/leddevice/LedDevice.cpp
- libsrc/leddevice/dev_net/LedDeviceNanoleaf.cpp
- libsrc/leddevice/dev_net/LedDeviceNanoleaf.h
- libsrc/leddevice/dev_net/LedDevicePhilipsHue.cpp
- libsrc/leddevice/dev_net/LedDevicePhilipsHue.h
- libsrc/leddevice/dev_spi/ProviderSpi.cpp
- libsrc/leddevice/schemas/schema-philipshue.json
**Summary**
- Alignment of PhilipsHue device to reworked device handling (QT Thread affinity)
- Incorporation of selected changes done by @SJunkies 
- Refactoring to have synchronous API call behaviour
- Refactoring in preparation of Hue Entertainment support
- Fixes on Hue Wizard
- Reduction of API-Calls (execute On/Off, Transition and Color update via one call)
- Fix: Calculate latch-time only for lights updated by hyperton
New feature
- Introduction of SSDP …
> Align Phillips Hue to reworked device handling

- assets/webconfig/js/ui_utils.js
Preventing a dead lock when the requested instance from local store is not running. 
If it is not running we will now delete the lastSelectedInstance and switch back to index 0.
**Summary**
> Check if requested Instance is running

- assets/webconfig/css/darkMode.css
- assets/webconfig/css/hyperion.css
- assets/webconfig/index.html
- assets/webconfig/js/content_index.js
- assets/webconfig/js/content_logging.js
- assets/webconfig/js/ui_utils.js
**Summary**
Introducing new Dark Mode. You can switch with a button on top. The value if dark mode is set or not is stored in localStorage on Client Browser. 
Resolves #744 
Some OS (iOS or Mac OS e.g.) can give the browser an information if system wide dark mode is set or not. If the OS shares this information, webui is set automatically to the mode. Manual overwrite is still possible by pressing button on the webui. This is valid as long the session in the client is open.
**The PR fulfills these …
> Introduce Dark Mode

- libsrc/grabber/x11/CMakeLists.txt
- src/hyperion-x11/CMakeLists.txt
- src/hyperiond/CMakeLists.txt
**Summary**
Maybe not necessary, but I had problems compiling hyperion.ng on macOS Catalina and got various `fatal error: 'X11/Xlib.h' file not found` x11-grabber errors, even after installing XQuartz, because X11 is no longer part of macOS. I'm not sure if other include paths like "/usr/X11/lib" are also needed, but these PR changes have helped fix the bugs.
To avoid wasting your time, it's best to open …
> OSX add x11 new include path

- assets/webconfig/i18n/de.json
- assets/webconfig/i18n/en.json
- assets/webconfig/js/content_index.js
- docs/yarn.lock
**Summary**
Allow the user to suppress default password warning,
in case they are happy to run hyperion without password access.
**Before**
**After**
> Suppress default password warning

- libsrc/leddevice/dev_serial/ProviderRs232.cpp
**Summary**
* ProviderRs232: checking for existence of device file does not work on windows.
* instead: construct QSerialPortInfo from device name and check, if it is not null.
When constructing QSerialPortInfo from device name, this constructor finds the
relevant serial port among the available ones according to the port name name,
and constructs the serial port info instance for that port.
(https://doc.qt.io/qt-5/qserialportinfo.html#QSerialPortInfo-2)
Fixes: #836 
**The PR fulfills these …
> use QSerialPortInfo to detect presence of a serial port (fix #836)

- CONTRIBUTING.md
**Summary**
Fix broken link to CompileHowto in documentation
> Fix broken link to CompileHowto in documentation

- libsrc/hyperion/HyperionIManager.cpp
- libsrc/leddevice/LedDeviceWrapper.cpp
- src/hyperion-aml/AmlogicWrapper.cpp
- src/hyperiond/hyperiond.cpp
**Summary**
Before :
(gdb) info threads 
Id   Target Id         Frame 
* 1    Thread 0x7ffff7fc8400 (LWP 8738) "hyperiond" 0x00007ffff3c22bf9 in __GI___poll (fds=0x55555611f8d0, nfds=7, timeout=62) at ../sysdeps/unix/sysv/linux/poll.c:29
2    Thread 0x7fffea135700 (LWP 8743) "QXcbEventReader" 0x00007ffff3c22bf9 in __GI___poll (fds=0x7fffea134ca8, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
3    Thread 0x7fffdf001700 (LWP 8744) "QDBusConnection" 0x00007ffff3c22bf9 in __GI___poll (fds=0x7fffd8019170, nfds=4, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
4    Thread 0x7fffde2e7700 (LWP 8745) "hyperiond" 0x00007ffff3c22bf9 in __GI___poll (fds=0x55555600a970, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
5    Thread 0x7fffdd981700 (LWP 8746) "QThread" …
> Show thread names in GDB for better debugging

- libsrc/effectengine/EffectEngine.cpp
**Summary**
The effects created by ````EffectEngine```` are stored in a container as soon as they are created and started :
int EffectEngine::runEffectScript(const QString &script, const QString &name, const QJsonObject &args, int priority, int timeout, const QString &origin, unsigned smoothCfg, const QString &imageData)
{
....
// create the effect
Effect *effect = new Effect(_hyperion, priority, timeout, script, name, args, imageData);
connect(effect, &Effect::setInput, _hyperion, &Hyperion::setInput, Qt::QueuedConnection);
connect(effect, &Effect::setInputImage, _hyperion, &Hyperion::setInputImage, Qt::QueuedConnection);
connect(effect, &QThread::finished, this, &EffectEngine::effectFinished);
connect(_hyperion, &Hyperion::finished, effect, &Effect::requestInterruption, …
> Fix leaking active events and a potential crash during quit

- .vscode/tasks.json
- CHANGELOG.md
- README.md
- cmake/nsis/template/NSIS.template.in
- cmake/packages.cmake
- src/hyperiond/CMakeLists.txt
- src/hyperiond/console.h
- src/hyperiond/main.cpp
**Summary**
Windows: Add option `-c` to hyperiond to create a console window with log output
> feat: Windows console window

- .azure.yml
- CompileHowto.md
- cmake/Dependencies.cmake
**Summary**
As explained in Issue #737, the OpenSSL dependencies for Windows are still missing.
Many thanks to @m-seker  for the hint.
> Fix OpenSSL dependencies for Windows

- include/db/DBManager.h
- include/db/InstanceTable.h
- libsrc/db/DBManager.cpp
**Summary**
DBManager: ORDER BY parameter added to getRecord/getRecords.
All instances are now sorted in ascending order using the instance field / ID.
The web interface gets an incorrect instance order, which causes further problems.
**Steps to reproduce:**
- create more than 1 instance, in my case, the new instance has become ID "1"
- create 1 or 2 more instances (with different names) and you will have 3-4 instances with IDs : 0,1,2,3
- delete instance with ID "1" and the remaining IDs are: 0,2,3
- create a new instance again (in my case, i used the same name from previouse deleted instance  again) and the IDs are now saved in DB order: 0,2,3,1
- start and switch to your last instance (with ID "1", sorted and displayed as 4. instance).
- If everything went to reproduce, the wrong …
> DBManager: ORDER BY parameter added to getRecord(s)

- assets/webconfig/js/content_logging.js
- include/hyperion/AuthManager.h
- include/utils/Logger.h
- libsrc/api/JsonAPI.cpp
- libsrc/flatbufserver/FlatBufferConnection.cpp
- libsrc/hyperion/ComponentRegister.cpp
- libsrc/hyperion/Grabber.cpp
- libsrc/hyperion/SettingsManager.cpp
- libsrc/utils/DefaultSignalHandler.cpp
- libsrc/utils/Logger.cpp
**Summary**
Fixes #723 and #874 
Changes :
- Make logger thread safe.
- Include timestamp in logs.
- Make logs look a bit more cleaner.
Example :
```
2020-07-18T23:10:08.975 hyperiond LEDDEVICE    : <DEBUG> ProviderSpi.cpp:46:init() | _baudRate_Hz [3000000], _latchTime_ms [0]
2020-07-18T23:10:08.975 hyperiond LEDDEVICE    : <DEBUG> ProviderSpi.cpp:47:init() | _spiDataInvert [0], _spiMode [0]
2020-07-18T23:10:08.975 hyperiond LEDDEVICE    : <DEBUG> LedDeviceSk6812SPI.cpp:45:init() | whiteAlgorithm : subtract_minimum
2020-07-18T23:10:08.975 hyperiond LEDDEVICE    : <ERROR> Device disabled, device 'sk6812spi' signals error: 'Failed to open device (/dev/spidev0.0). Error message: No such file or directory'
2020-07-18T23:10:08.981 hyperiond EFFECTENGINE : <INFO> Run effect "Rainbow swirl fast" …
```
> Fix logger

- include/utils/Image.h
- include/utils/ImageData.h
- libsrc/hyperion/Hyperion.cpp
- libsrc/utils/ImageResampler.cpp
**Summary**
Use implicit sharing for Image data to eliminate redundant copies.
PS : A quick profiling says that we spend most of our time during ImageResampler::process(), it is mostly color conversion code. We can vectorize that code but portability is a concern. Maybe we can start with common SIMD instruction sets and fallback to normal for others. I did a quick test and my VM takes approximately 500us to resample the image. I tried implementing it with AVX2 and it is now around 50us.
Al in all, those number are no concern at all but optimization is always fun.
If yes, …
> Some optimizations

- include/effectengine/Effect.h
- include/hyperion/Hyperion.h
- include/webserver/WebServer.h
- libsrc/effectengine/Effect.cpp
- libsrc/effectengine/EffectModule.cpp
- libsrc/ssdp/SSDPHandler.cpp
- libsrc/webserver/WebServer.cpp
- src/hyperiond/hyperiond.cpp
**Summary**
Fox some data synchronization error
> Fix some data races

- include/utils/ImageData.h
- libsrc/grabber/qt/QtGrabber.cpp
- libsrc/utils/ImageResampler.cpp
**Summary**
resize() is forgotten for image before using
> Fix Qt screenhot crash

- CHANGELOG.md
- include/commandline/Parser.h
- libsrc/api/JsonAPI.cpp
- libsrc/utils/Process.cpp
- src/hyperiond/detectProcess.h
- src/hyperiond/main.cpp
**Summary**
**restart** RPC fails because ````execve```` doesn't return and blocks the process. Hence we don't return a response to the caller. Also, ````hyperion->freeObjects()```` is called on a totally wrong thread, which causes a crash.
This PR introduces a different path for restarting Hyperion. It starts a new instance of Hyperion in a detached state with a special internal command line argument (**--wait-hyperion**). New instance sees that **--wait-hyperion** argument is set and waits until previous Hyperion exits. Old instance gracefully quits application. Then new instance continues with normal execution.
**Does this PR …
> Fix 'Restart' RPC command

- include/hyperion/ComponentRegister.h
- include/hyperion/Hyperion.h
- include/leddevice/LedDevice.h
- include/leddevice/LedDeviceWrapper.h
- libsrc/api/API.cpp
- libsrc/api/JsonAPI.cpp
- libsrc/api/JsonCB.cpp
- libsrc/hyperion/Hyperion.cpp
- libsrc/leddevice/LedDeviceWrapper.cpp
> Fix some more threading errors

- CMakeLists.txt
- cmake/nsis/icon.rc
- cmake/win/win.rc.in
- cmake/win/win_rc.cmake
- src/hyperion-qt/CMakeLists.txt
- src/hyperion-remote/CMakeLists.txt
- src/hyperiond/CMakeLists.txt
**Summary**
- Add more meta to all binaries
- Just `hyperiond` is now promoted to be a gui app, `hyperion-remote` and `hyperion-qt` run now properly again in terminal scope (no window and proper output)
- Note: It's not possible to omit the language field
The file view
The "Autostart-App" page of Windows 10. Previous it was just "hyperiond"
To …
> feat(win): Add binary meta

- CHANGELOG.md
- assets/webconfig/js/hyperion.js
> Websocket fix for SSL reverse proxies

- include/hyperion/Hyperion.h
- include/ssdp/SSDPDiscover.h
- libsrc/api/JsonAPI.cpp
- libsrc/boblightserver/BoblightClientConnection.cpp
- libsrc/boblightserver/BoblightServer.cpp
- libsrc/bonjour/bonjourservicebrowser.cpp
- libsrc/bonjour/bonjourserviceregister.cpp
- libsrc/bonjour/bonjourserviceresolver.cpp
- libsrc/effectengine/EffectEngine.cpp
- libsrc/grabber/v4l2/V4L2Grabber.cpp
- libsrc/grabber/v4l2/V4L2Wrapper.cpp
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/SettingsManager.cpp
- libsrc/jsonserver/JsonServer.cpp
- libsrc/leddevice/LedDevice.cpp
- libsrc/leddevice/dev_net/ProviderRestApi.cpp
- libsrc/leddevice/dev_other/LedDevicePiBlaster.cpp
- libsrc/leddevice/dev_serial/LedDeviceAdalight.cpp
- libsrc/leddevice/dev_serial/LedDeviceAdalight.h
- libsrc/leddevice/dev_serial/LedDeviceKarate.cpp
- libsrc/leddevice/dev_serial/ProviderRs232.cpp
- libsrc/ssdp/SSDPDiscover.cpp
- src/hyperiond/hyperiond.cpp
**Summary**
Get rid of old style Qt connections.
+
Some minor fixes.
> Modernize Qt connections

- assets/webconfig/js/content_grabber.js
- assets/webconfig/js/ui_utils.js
- assets/webconfig/js/wizard.js
- libsrc/grabber/xcb/XcbGrabber.cpp
- libsrc/hyperion/GrabberWrapper.cpp
- libsrc/leddevice/dev_net/LedDeviceYeelight.cpp
- src/hyperion-qt/QtWrapper.h
> Fix some LGTM warnings

- dependencies/CMakeLists.txt
**Summary**
Build against shared system protobuffer and flatbuffer libs is completely broken, at least if AMLOGIC is turned off. Until recently that was also the case for mbedtls, however got fixed (https://github.com/hyperion-project/hyperion.ng/issues/883).
I'm confused about the so many AMLOGIC specific build rules anyway. Maybe don't necessarily see this PR as ready to be merged, but more to raise a discussion about those AMLOGIC specific build rules. They really seem unnecessary to me.
Actually, to me it looks like somebody needed to have the system lib support running on AMLOGIC but didn't care about everything else. So, for the rules I had to touch I dropped the AMLOGIC specific rules.
**Does this PR introduce a …
> drop (some) AMLOGIC specfic rules, fix buid against flat-+/protobuf system libs

- include/api/JsonAPI.h
- libsrc/api/JsonAPI.cpp
> Return tan to API requests whenever possible

- include/flatbufserver/FlatBufferServer.h
- libsrc/flatbufserver/FlatBufferServer.cpp
- libsrc/jsonserver/JsonServer.cpp
- libsrc/webserver/WebServer.cpp
> ENABLE_AVAHI is not included in WebServer

- assets/webconfig/i18n/de.json
- assets/webconfig/i18n/en.json
- assets/webconfig/js/content_leds.js
- docs/docs/en/user/LedDevices.md
- libsrc/hyperion/schema/schema-device.json
- libsrc/leddevice/LedDeviceSchemas.qrc
- libsrc/leddevice/dev_spi/LedDeviceSK9822.cpp
- libsrc/leddevice/dev_spi/LedDeviceSK9822.h
- libsrc/leddevice/schemas/schema-sk9822.json
**Summary**
Support for SK9822 type LEDs is added with global brightness control feature.
SK9822 type LEDs allow for 5-Bit (32 level) brightness adjustment using simultaneous regulation of R/G/B LED current. This allows for fine granular control of output light levels while maintaining full 8-Bit grayscale resolution. Even though the LED type is generally compatible with APA 102 style LEDs, the constant current regulation function shows compatibility issues with the existing implementation of the APA 102 control protocol. 
This PR introduces support for SK9822 devices via SPI. Maximum current (brightness) level is user controllable on the 32 value scale. Also, low luminosity (near black) colors below a user defined threshold are converted such that optimal grayscale resolution is archived …
> Support SK9822 type LEDs with adaptive brightness control via SPI

- include/utils/QStringUtils.h
- libsrc/boblightserver/BoblightClientConnection.cpp
- libsrc/boblightserver/BoblightClientConnection.h
**The amount of memory allocations in BoblightClientConnection is reduced drastically.**
BoblightClientConnection used to perform a huge amount of memcopy-operations - mostly involving read only string data – that led to high CPU usage. Now QStringRef is used to store tokenized Boblight messages instead of creating read-only copies of such strings. 
The parsing of RGB values (given as float-strings) is optimized to be allocation-free. This is archived using a native (thus performant) implementation based on QChar character values and mostly int-arithmetic.
If yes, please …
> boblight: reduce cpu time spent on memcopy and parsing rgb values

- src/hyperion-osx/hyperion-osx.cpp
- src/hyperion-qt/hyperion-qt.cpp
**Summary**
This fixes the display argument in hyperion-qt, so it actually uses the display given to the program through argument.
> FIX: display argument in hyperion-qt

- CHANGELOG.md
- libsrc/leddevice/dev_serial/LedDeviceKarate.cpp
The Karatelight integration only allowed a 16-LED setup. This was actually only possible when using a separately sold "expansion pack" to the Karatelight. Without this, only 8 channels are supported. This minimal change also allows an 8-channel setup. I have tested the change on my setup and can confirm it working. An 8-channel controller will not work with the unchanged code, since it will not accept data for 16 channels.
**Summary**
If adding a **new feature**, …
> Allow 8-LED configuration for KarateLight

- include/utils/hyperion.h
**Summary**
Fix issue #909 - "Set many LEDs on the horizontal bottom of the layout causes Hyperion to crash forever"
Do Hight :Width ratio correction first and then scale to max 80px.
This will ensure the height is not zero and fix the divide by zero issue.
To avoid wasting your time, it's best to open a **feature request issue** first and wait …
> Fix issue #909 - "Set many LEDs on the horizontal bottom crashes Hyperion"

- libsrc/leddevice/dev_spi/LedDeviceSK9822.cpp
According to this article https://cpldcpu.wordpress.com/2016/12/13/sk9822-a-clone-of-the-apa102/ sk9822 requires zero segment at the end of frame to force led update. Similar solutions are applied in other libraries. Hyperion.ng ends frame with 0xFF which was OK for APA102 but not for sk9822 since support for it was included.
- [ x] Bugfix
- [x ] No
**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO …
> Fix for sk9822 frame sufix

- include/hyperion/PriorityMuxer.h
- libsrc/api/JsonCB.cpp
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/PriorityMuxer.cpp
**Summary**
The "activeStateChanged" signal in the PriorityMuxer was removed because it caused duplicate JsonCB signals.
Details in issue #993 .
Fixes: #993
> Fix reopened issue 993

- CHANGELOG.md
- docs/docs/en/api/Detect.md
- docs/docs/en/api/Guidelines.md
- docs/docs/en/json/Authorization.md
- docs/docs/en/json/Control.md
- docs/docs/en/json/README.md
- docs/docs/en/json/ServerInfo.md
- docs/docs/en/json/Subscribe.md
**Summary**
The  Hyperion JSON API docs are really great -- and I've used them extensively. I wanted to improve them by taking a pass and trying to make them a bit crisper and more smooth sounding.
Almost nothing of consequence is changed here -- this is almost all tone / style / linguistic, which hopes to make them easier to read. Perhaps the one exception is removing the reference to `plugins`, which are not supported in reality as far as  I can tell.
If adding …
> Localize/stylize/freshen the en JSON API docs

- libsrc/leddevice/dev_net/LedDeviceCololight.cpp
- libsrc/ssdp/SSDPDiscover.cpp
**Summary**
Fixes the splitting of domain from hostname.
Code considers now, if an IP-Address is part of the hostname.
Address issue raised in forum:
https://hyperion-project.org/threads/how-to-setup-hyperion-with-a-yeelight-solution.3342/#post-29249
To avoid wasting your time, it's best to open a **feature request issue** first and wait for …
> Fix hostname/domain split

- libsrc/leddevice/schemas/schema-ws2801.json
**Summary**
One raspberry PI can drive several LED strips on different GPIO ports. Until now only spidev0.0 or spidev0.1 could be selected. With this change a second LED strip can be controlled and selected in the Hyperion web interface.
For this purpose it is necessary to enable the additional GPIOs in the Raspberry. For this purpose we add the following line in the /boot/config.txt or change it accordingly.
`dtoverlay=spi1-3cs`
Then we restart the Raspberry with `shutdown -r -f now`.
After:
**The PR …
> Add spidev1.0 and spidev1.1 device for Raspberry Pi WS2801 schema

- include/hyperion/SettingsManager.h
- libsrc/hyperion/SettingsManager.cpp
**Summary**
- Fix that global settings were not correctly reflected across instances after updates in other non default instance
Configuration is now read from database which takes care of global and instance specific configurations, rather than using an instance's cache.
To avoid wasting your time, it's best to open a **feature request issue** …
> Fix #1131 - Have Global (Grabber) settings reflected correctly in non-default instances

- CHANGELOG.md
- libsrc/leddevice/dev_net/LedDevicePhilipsHue.cpp
**Summary**
For Hue, in stream mode, black produces a XY of (0,0).
However, if min brightness is configured, it is nonetheless applied, which leads to blue (closest to 0,0 in gamut).
This forces brightness to 0 if XY = (0,0) 
> FIX: [hue] XY == 0 => bri  = 0

- libsrc/protoserver/ProtoClientConnection.cpp
- libsrc/protoserver/ProtoClientConnection.h
- libsrc/protoserver/ProtoServer.cpp
**Summary**
utils/Logger.h contains a preprocessor macro Error() for easy logging.
However, the upstream protobuf/io/coded_stream.h also defines a private
function Error() in one of its classes that conflicts with this macro.
Thus, unfortunate include orders result in a build error. This commit
reorders the includes to prevent the error. It also defines an extra
`#undef Error` before including upstream protobuf to make the problem
more visible (a compiler error would not point to an obscure place
somewhere in protobuf but to the usage of the Error() macro within
Hyperion itself).
Fixes: #882
**Does this PR introduce a breaking …
> Proto*: fix Error macro conflict

- CHANGELOG.md
- include/effectengine/Effect.h
- libsrc/effectengine/Effect.cpp
- libsrc/effectengine/EffectModule.cpp
**Summary**
An effect timing out wouldn't make hyperion.abort() return True in an effect script. This updates the effect module to reflect this.
Fixes #1013
If changing the UI of web configuration, please provide the **before/after** screenshot: **n/a**
> Interrupt effect on timeout

- assets/webconfig/i18n/de.json
- assets/webconfig/i18n/en.json
- libsrc/leddevice/dev_serial/ProviderRs232.cpp
**Summary**
This PR introduces two changes (both should improve usability):
QtSerialPort accepts only certain names as SerialPort devices, not
paths. Guessing this names can be cumbersome so give some hint in the
log, if the given device name cannot be detected.
Even if the normal Kodi webinterface is activated and capable of
receiving JSON RPC calls (on port 8080), the js in Hyperion sets the
port to 9090 (normally only accessible via localhost). Since the js code
is executed on the users device, Kodi denies access even if Hyperion and
Kodi are installed on the same device.
This change helps in this situation by pointing to the correct Kodi setting.
Unfortunately, I'm only able to modify English and German.
maybe …
> Extend logging and error reporting

- libsrc/webserver/CMakeLists.txt
**Summary**
When using a cmake directory that is not a subfolder of the repository
root folder the current path replacement logic for webresources does not
work. This commit makes the replacement pattern also relative to the
build directory.
Reproduce with:
git clone hyperion-repo
mkdir build; cd build
cmake ../hyperion-repo
Without this chance the build itself succeeds but browsing the
webinterface results in:
404 - Requested file: index.html
Related: #834
If …
> webserver/Cmake: fix out-of-tree build

- assets/firmware/arduino/adalight/adalight.ino
**Summary**
Adalight
- Fix LED Num for non analogue output
- Send back number of LED configured
Addresses issue reported via forum:
https://hyperion-project.org/threads/first-led-always-on-with-arduino. …
> Adalight - Fix LED Num for non analogue output

- CHANGELOG.md
- include/utils/WaitTime.h
- libsrc/hyperion/schema/schema-device.json
- libsrc/leddevice/LedDevice.cpp
- libsrc/leddevice/dev_net/LedDeviceAtmoOrb.cpp
- libsrc/leddevice/dev_net/LedDeviceCololight.cpp
- libsrc/leddevice/dev_net/LedDeviceNanoleaf.cpp
- libsrc/leddevice/dev_net/LedDeviceNanoleaf.h
- libsrc/leddevice/dev_net/LedDevicePhilipsHue.cpp
- libsrc/leddevice/dev_net/LedDeviceWled.cpp
- libsrc/leddevice/dev_net/LedDeviceWled.h
- libsrc/leddevice/dev_net/LedDeviceYeelight.cpp
- libsrc/leddevice/dev_net/LedDeviceYeelight.h
- libsrc/leddevice/dev_net/ProviderRestApi.cpp
- libsrc/leddevice/dev_net/ProviderRestApi.h
- libsrc/leddevice/dev_serial/LedDeviceAtmo.cpp
- libsrc/leddevice/dev_serial/LedDeviceAtmo.h
- libsrc/leddevice/dev_serial/LedDeviceKarate.cpp
- libsrc/leddevice/dev_serial/LedDeviceKarate.h
- libsrc/leddevice/schemas/schema-wled.json
**Summary**
- WLED: Support of ["live" property] (https://github.com/Aircoookie/WLED/issues/1308), addresses #1095
- WLED: Support storing/restoring state, fixes #1101 
- LED-Devices: Allow to get properties for Atmo and Karatedevices to limit LED numbers configurable
- LED-Devices: Add timeouts for REST-API calls
- Nanoleaf: Consider Nanoleaf-Shape Controlers
- LED-Devices: Show HW-Ledcount in all setting levels
- LED-Hue: Minor fix of setColor command
- Nanoleaf: Fix,if external control mode cannot be set
If yes, please describe the impact and migration path for existing …
> LEDDevices - WLED enhancements and minor fixes

- include/effectengine/Effect.h
- include/effectengine/EffectEngine.h
- include/hyperion/BGEffectHandler.h
- include/hyperion/Hyperion.h
- include/hyperion/PriorityMuxer.h
- include/utils/hyperion.h
- libsrc/effectengine/Effect.cpp
- libsrc/effectengine/EffectEngine.cpp
- libsrc/effectengine/EffectModule.cpp
- libsrc/hyperion/PriorityMuxer.cpp
- src/hyperiond/systray.cpp
- src/hyperiond/systray.h
**Summary**
- Fixes#1181, where Effects were did not start when trigger from from tray
- Have named constants Fore-/Background priorities and no timeouts for effects 
- Populate setEffect parameters to have a clearly defined behaviour
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before …
> Fix 1181 - Effects were not started from tray

- CHANGELOG.md
- assets/webconfig/i18n/en.json
**Summary**
Modify description of the "LED Test" effect
See #1229 - "LED Test" effect description is in wrong order
**before**
**after**
> Fixes:  #1229

- include/hyperion/BGEffectHandler.h
**Summary**
Stop background effect, when it is overlaid by another priority.
Otherwise the background effect will  continuously run in the background and eats up resources unnecessarily.
> Stop background effect, when it gets out of scope

- CHANGELOG.md
- libsrc/leddevice/dev_net/LedDevicePhilipsHue.cpp
**Summary**
Add basic support for the Philips Hue Play Gradient Lightstrip. This is a ready-to-use lightstrip for TVs with seven dedicated segments. The Model ID is LCX001. Currently dedicated segment control is only possible via Entertainment API.
Adding full support is work-in-progress. But basically it's just changing the light slot type in the Entertainment API stream message to 0x01 and using the ID 0x00 to 0x06 to address the single segments. This is not officially documented yet on meet-hue.com but could be found by experimenting a little ;)
If yes, please describe the …
> Initial support for Hue Play Gradient Lightstrip

- libsrc/hyperion/PriorityMuxer.cpp
**Summary**
- Fix #1216 - Clear All occasionally does not work
Fixes #1216, #1113, #993
> Fix #1216 - Clear All occasionally does not work

- libsrc/webserver/WebSocketClient.cpp
**Summary**
WebSocket OpCode were forgotten when sending split frames.
> websocket crashes fixed

- assets/webconfig/js/wizard.js
- libsrc/leddevice/dev_net/ProviderUdpSSL.cpp
**Summary**
Fix Philips Hue wizard (#1276 )
Fix AtmoOrb wizards
Fixes #1276
> Fix Philips Hue and AtmoOrb wizards

- assets/webconfig/content/conf_leds.html
- assets/webconfig/i18n/en.json
- assets/webconfig/js/content_grabber.js
- assets/webconfig/js/content_leds.js
- assets/webconfig/js/content_logging.js
- assets/webconfig/js/ui_utils.js
- include/hyperion/HyperionIManager.h
- include/utils/SysInfo.h
- libsrc/api/JsonAPI.cpp
- libsrc/grabber/video/v4l2/V4L2Grabber.cpp
- libsrc/leddevice/dev_net/LedDeviceTpm2net.cpp
- libsrc/leddevice/dev_net/LedDeviceTpm2net.h
- libsrc/leddevice/dev_rpi_pwm/LedDeviceWS281x.cpp
- libsrc/leddevice/dev_rpi_pwm/LedDeviceWS281x.h
- libsrc/leddevice/dev_spi/ProviderSpi.cpp
- libsrc/leddevice/schemas/schema-ws281x.json
- libsrc/ssdp/SSDPHandler.cpp
- libsrc/utils/SysInfo.cpp
**Summary**
**Fixes**
- SPI - Free allocated memory in case of invert
- Tpm2.Net - Free allocated memory
- Minor other corrections
**Added**
- WS281x - Provide speaking error messages when Hyperion is not run with root privileges
- WS281x - Ensure that a device cannot be configured via the UI when Hyperion is not run with root privileges
- WS281x - Update DMA default as per rpi_ws281x [recommendation](https://github.com/jgarff/rpi_ws281x)
- Added used config path and "is run under root/admin" to system info screen
If yes, please describe the impact and migration path for …
> LED-Device updates

- .vs/launch.vs.json
- assets/webconfig/js/content_index.js
- assets/webconfig/js/content_leds.js
- assets/webconfig/js/ledsim.js
- libsrc/api/JsonAPI.cpp
- libsrc/leddevice/dev_net/LedDeviceWled.cpp
**Summary**
- Refactor/Optimization: Load configuration of last instance used when loading the UI page
- Refactor: Streamline API requests to avoid unnecessary invocations (Correct issue introduced by PR1213)
- Disable LED update streaming, if LED updates are not required
- Sync. Video-Streaming between Layout and Simulation
**UI page initialisation sequence**
```
content_index.js - document.ready
initWebSocket()
-> websocket.onopen
trigger open
-> open
requestRequiresAdminAuth()
-> cmd-authorize-adminRequired
requestRequiresDefaultPasswortChange()
-> cmd-authorize-newPasswordRequired
requestAuthorization()/requestTokenAuthorization()
-> cmd-authorize-login
requestServerConfigSchema()
-> cmd-config-getschema
requestTokenInfo();
requestGetPendingTokenRequests();
instanceSwitch() …
```
> Correct PR1312 and LEDSim fixes

- assets/webconfig/i18n/en.json
- assets/webconfig/js/content_leds.js
- libsrc/leddevice/dev_net/LedDeviceUdpRaw.cpp
- libsrc/leddevice/dev_net/LedDeviceUdpRaw.h
- libsrc/leddevice/dev_net/LedDeviceWled.cpp
**Summary**
- Limit maximum LEDs numberfor WLED to 490 
- Limit maximum LEDs number for UDP-Raw to 490 
Background: The current UDP-raw protocol  is not capable of handling loss of fragmented packages.
Therefore the number of LEDs is limited to have only one package per update.
To avoid wasting your time, it's best to open a **feature request …
> Limit maximum LEDs number for WLED and UDP-Raw

- CHANGELOG.md
- libsrc/utils/DefaultSignalHandler.cpp
**Summary**
libcrypto performs cpu feature checks on ARM platforms, by calling `OPENSSL_cpuid_setup`.
In there, it tries to call various instructions and traps `illegal instructions` aka. non-existing instructions itself.
However, as hyperion.ng also tries to trap all signals, the call inside libcrypto is propagated and hyperiond gets killed by itself.
This patch lets execution proceed, even when `SIGILL` occurs.
References:
- libcrypto OPENSSL_cpuid_setup: https://github.com/openssl/openssl/blob/954f45ba4c504570206ff5bed811e512cf92dc8e/crypto/armcap.c#L183
If yes, please …
> libsrc/utils: Do not catch SIGILL signal

- assets/webconfig/i18n/en.json
- assets/webconfig/js/content_leds.js
- config/hyperion.config.json.default
- include/leddevice/LedDevice.h
- libsrc/hyperion/schema/schema-device.json
- libsrc/leddevice/LedDevice.cpp
**Summary**
- Allow to disable switching LEDs on during startup (#1390)
Fixes #1390
> Allow to disable switching LEDs on during startup

- libsrc/leddevice/CMakeLists.txt
* Checks whether glibc has former librt function 'clock_gettime' included (that's since glibc 2.17).
* glibc <2.17 requires linking with 'librt' explicitly.
Reference: https://github.com/bminor/glibc/blob/b92a49359f33a461db080a33940d73f47c756126/time/clock_gettime.c#L32-L37
**Summary**
> CMake: build-time test - backwards compatibility with older glibc

- libsrc/utils/ColorSys.cpp
- libsrc/utils/OkhsvTransform.cpp
**Summary**
The Oklab reference implementation (#1477) can under some circumstances output RGB colors (components of type double) with slightly negative values. (I'm not sure if this is due to imprecise operations or just the nature of the internal gamut mapping.)
When converting those double components back to bytes a rollover could occur leaving the affected component with a value of `255` instead of the intended `0`.
This PR fixes that issue by clamping the components just before type conversion happens.
And sorry for not catching this with the initial PR.
If yes, please …
> Oklab: Fix rollover error

- CHANGELOG.md
- LICENSE
- assets/webconfig/js/content_index.js
- assets/webconfig/js/content_logging.js
- assets/webconfig/js/ui_utils.js
- assets/webconfig/js/wizard.js
- cmake/FindWindowsSDK.cmake
- cmake/packages.cmake
- dependencies/CMakeLists.txt
- include/mdns/MdnsBrowser.h
- include/utils/NetUtils.h
- include/utils/WeakConnect.h
- include/utils/hyperion.h
- include/utils/jsonschema/QJsonUtils.h
- libsrc/api/JsonAPI.cpp
- libsrc/utils/jsonschema/QJsonSchemaChecker.cpp
- src/hyperion-aml/hyperion-aml.cpp
- src/hyperion-dispmanx/hyperion-dispmanx.cpp
- src/hyperion-osx/hyperion-osx.cpp
- src/hyperion-remote/JsonConnection.cpp
- src/hyperiond/CMakeLists.txt
- test/CMakeLists.txt
- test/TestImage2LedsMap.cpp
**Summary**
***Added***
- cmake support of libcec without version in lib-name
***Changed***
- Various clean-ups
***Fixed***
- Hue-Wizard: In case auto discovery failed, port 80 was not used as default (#1544)
- Send only one reply per Start Instance request (#1551)
- Add instance# in JSON-API replies (aligning to #1504 behaviour)
- hyperion-remote: Extracting reply for a configGet request correctly (#1555)
If adding a **new feature**, the PR's description …
> Various Fixes/Updates

- assets/webconfig/js/content_leds.js
- libsrc/leddevice/dev_rpi_pwm/LedDeviceWS281x.cpp
**Summary**
Fix ws281x - Update logic to identify is user is admin and disable device configuration if not
Fixes #1621
> ws281x - Update logic to identify is user is admin

- CHANGELOG.md
- libsrc/leddevice/dev_net/LedDevicePhilipsHue.cpp
- libsrc/leddevice/dev_net/ProviderRestApi.cpp
- libsrc/leddevice/dev_net/ProviderRestApi.h
**Summary**
Fixed self-signed certificate handling.
Implemented “trust on first use” certificate handling as per Philip Hues developer guidance.
- X] No
Fixes #1637
> Hue - Fix self-signed certificate handling

- src/hyperiond/hyperiond.cpp
**Summary**
build with out MDNS does not work:
```
hyperion.ng-git/src/hyperion.ng/src/hyperiond/hyperiond.cpp:298:9: error: ‘_mDNSProvider’ was not declared in this scope; did you mean ‘RRProvider’?
298 |         _mDNSProvider->thread()->start();
```
To avoid wasting your time, it's best to open a **feature request issue** first and wait for …
> add missing ENABLE_MDNS in hyperiond.cpp

- libsrc/webserver/StaticFileServing.cpp
**Summary**
Add workaround that Content type is wrongly resoved (see https://bugreports.qt.io/browse/QTBUG-97392)
fixes #1692
> Add workaround for issue #1692

- include/grabber/video/mediafoundation/MFGrabber.h
- include/grabber/video/v4l2/V4L2Grabber.h
- libsrc/grabber/video/mediafoundation/MFGrabber.cpp
- libsrc/grabber/video/v4l2/V4L2Grabber.cpp
**Summary**
This PR will simply invert logic of variable _noSignalDetected in V4L2Grabber.cpp and MFGrabber.cpp, as current logic is IMHO very confusing.
This is my first PR ever, i'm still trying to …
> Change confusing logic

- libsrc/webserver/QtHttpClientWrapper.cpp
- libsrc/webserver/QtHttpClientWrapper.h
**Summary**
Fix hyperion-project#1688 - Fragmented http-Headers 
Fixes #1688
> Fix #1688 - Fragmented http-Headers

- CHANGELOG.md
- assets/webconfig/js/wizards/LedDevice_philipshue.js
- libsrc/leddevice/LedDeviceWrapper.cpp
- libsrc/leddevice/dev_net/LedDevicePhilipsHue.cpp
- libsrc/leddevice/dev_net/ProviderRestApi.cpp
**Summary**
Fixed: Philip Hue APIv2 support without Entertainment group defined (#1742)
fixes: #1742
> Fix Philip Hue APIv2 support without Entertainment group defined

- libsrc/grabber/video/EncoderThread.cpp
**Summary**
If pixelfomat BGR24 is selected in V4L2 grabber, the image is flipped horizontally (with flipmode set to None). This PR will fix that. However, in my opinion this special treatment is not necessary for BGR24 and can be removed completely. But I'm not 100% sure, maybe a developer can take a look.
wbr
To avoid wasting your time, it's …
> Fix flipmode for BGR24 special handling

- include/utils/PixelFormat.h
- libsrc/grabber/video/mediafoundation/MFSourceReaderCB.h
- libsrc/grabber/video/v4l2/V4L2Grabber.cpp
- libsrc/utils/ImageResampler.cpp
**Summary**
- RGB24 / BGR24 / BGR16 on top of #1748 
> RGB24 and BGR24 cleanup

- doc/development/CompileHowto.md
Update macOS build instructions for QT6 and add missing dependency of pkg-config
**Summary**
> Update CompileHowto.md for macOS

- libsrc/grabber/video/EncoderThread.cpp
- libsrc/grabber/video/mediafoundation/MFSourceReaderCB.h
**Summary**
Hi,
i would like to add two comments to MF-grabber to clarify why image data is processed as BGR24, even though Microsoft Media Foundation (MMF) does not support this pixel format (https://learn.microsoft.com/en-us/windows/win32/medfound/video-subtype-guids#uncompressed-rgb-formats). I'm sure they'll be helpful to others looking at the code.
wbr
**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO …
> MF-grabber: Add some clarifying comments

- .github/workflows/codeql.yml
- CHANGELOG.md
- assets/webconfig/i18n/en.json
- libsrc/leddevice/dev_serial/LedDeviceAdalight.cpp
- libsrc/leddevice/dev_serial/LedDeviceAdalight.h
- libsrc/leddevice/schemas/schema-adalight.json
**Summary**
- Support for Skydimo devices (being an Adalight variant)
fixes #1764
> Skydimo LedDevice support

- assets/webconfig/i18n/en.json
- assets/webconfig/js/content_leds.js
- libsrc/hyperion/schema/schema-device.json
- libsrc/leddevice/LedDeviceSchemas.qrc
- libsrc/leddevice/dev_serial/LedDeviceAdalight.cpp
- libsrc/leddevice/dev_serial/LedDeviceSkydimo.cpp
- libsrc/leddevice/dev_serial/LedDeviceSkydimo.h
- libsrc/leddevice/schemas/schema-adalight.json
- libsrc/leddevice/schemas/schema-skydimo.json
**Summary**
- Add Skydimo as an own device after PoC via  #1765 was successful.
> Skydimo as own device

- libsrc/leddevice/dev_serial/LedDeviceSkydimo.cpp
**Summary**
- Fix Skydimo - Populating output buffer was missed while creating separate device
Fixes #1801
> Fix Skydimo - Populate output buffer

- include/flatbufserver/FlatBufferServer.h
- include/utils/ImageResampler.h
- libsrc/flatbufserver/FlatBufferClient.cpp
- libsrc/flatbufserver/FlatBufferClient.h
- libsrc/flatbufserver/FlatBufferServer.cpp
- libsrc/flatbufserver/hyperion_request.fbs
- libsrc/hyperion/schema/schema-flatbufServer.json
**Summary**
- Support NV12 format on Flat-Buffer to maintain interface consistency
- Support SizeDecimation on Flat-Buffer input images
> Support NV12 format on Flatbuffer

- libsrc/leddevice/dev_net/ProviderRestApi.cpp
- libsrc/leddevice/dev_net/ProviderRestApi.h
**Summary**
- Provide more details on "Trust on first use" certificates in log, esp. if certificate cannot be stored
fixes #1811
> Provide more details on pinned certificate files

- assets/webconfig/js/content_leds.js
- libsrc/leddevice/LedDeviceSchemas.qrc
- libsrc/leddevice/dev_spi/LedDeviceHD108.cpp
- libsrc/leddevice/dev_spi/LedDeviceHD108.h
- libsrc/leddevice/schemas/schema-hd108.json
**Summary**  
This PR implements support for 16-bit HD108 LEDs in HyperionNG. It makes it possible to use the highspeed LEDs and adds new configuration options for HD108 LEDs.
If changing the UI of web configuration, please provide the **before/after** screenshot:  
N/A
If yes, please describe the impact and migration path for existing setups:  
N/A
**The PR fulfills these requirements:**  
**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**  
**Other information:**  
This …
> Implemented 16Bit HD108-Leds in HyperionNG

- CHANGELOG.md
- libsrc/leddevice/dev_net/LedDeviceNanoleaf.cpp
**Summary**
Some Nanoleaf LEDs are in a strip
The Nanoleaf code calculates a position for each LED and stores each LED ID in a map, keying of X,Y.
With the layouts provided, LEDs have "overlapping" positions in X,Y in the corners.
This means that multiple LEDs land in the same map entry, overwriting existing IDs in the map.
At the end of the Nanoleaf init function is code to check the size of the map matches the number of LEDs.
In my setup, this was failing because of the 'overwritten' IDs aren't counted.
To fix this I've changed the value of the Map to be a vector of IDs, which allows for duplicates to be tracked correctly.
I've also improved the logging slightly to show that duplicates have been found.
This change is expected to have zero impact on any previously working configuration, …
> Store a list of arrays at each location so duplicates aren't lost

- libsrc/flatbufserver/FlatBufferClient.cpp
- libsrc/flatbufserver/FlatBufferClient.h
- libsrc/flatbufserver/FlatBufferConnection.cpp
**Summary**
- Flatbufferclient: Remove costly unpack and streamline code
- Fix - Retries are not done when connection is destructed
> Fixing Flatbuffer Processing

- assets/webconfig/js/ui_utils.js
- doc/development/JSON-API _Commands_Overview.md
- include/api/JsonApiCommand.h
- include/db/SettingsTable.h
- include/hyperion/SettingsManager.h
- include/utils/jsonschema/QJsonUtils.h
- libsrc/api/API.cpp
- libsrc/api/JsonAPI.cpp
- libsrc/api/JsonCallbacks.cpp
- libsrc/api/JsonInfo.cpp
- libsrc/db/DBConfigManager.cpp
- libsrc/db/DBMigrationManager.cpp
- libsrc/db/SettingsTable.cpp
- libsrc/forwarder/MessageForwarder.cpp
- libsrc/hyperion/HyperionIManager.cpp
- libsrc/hyperion/schema/schema-effects.json
- libsrc/hyperion/schema/schema-forwarder.json
- libsrc/hyperion/schema/schema-ledConfig.json
- libsrc/utils/JsonUtils.cpp
- libsrc/utils/jsonschema/QJsonSchemaChecker.cpp
- src/hyperiond/hyperiond.cpp
**Summary**
Fix - Correct JSON processing
Fix - Show effectsconfigurator menu entry, only if effectengine is available
Improvements
- JSON getconfig API - allow filter to exclude elements via "null" 
- Update schemas to accept empty arrays
- Stop WebServer before JSON API to avoid blocking calls by UI
hyperion.ng/commit/dbfc59a28c09ff3bd91fca81d588c1d0a1bba725)
- [] Docs
**PLEASE DON'T FORGET TO ADD YOUR …
> Fixing configuration migration issues

- assets/webconfig/js/content_index.js
**Summary**
- Fixed Re-add SwitchToMenuItem function removed on error
Reported: https://hyperion-project.org/forum/index.php?thread/14273-json-commands-for-smoothing-parameters/&postID=53973#post53973
> Re-add SwitchToMenuItem function

- CHANGELOG.md
- assets/webconfig/js/content_grabber.js
- assets/webconfig/js/ui_utils.js
**Summary**
- USB Grabber - Default hardware control properties are now applied when a new USB grabber is selected
This should avoid that grabbers are perceived as not working, while a default zero brightness just result in back images streamed.
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval …
> Ensure grabber default  hardware contols are used
