hyperion-project/hyperion.ng

- PULL_REQUEST_TEMPLATE
IMPORTANT: Please don´t commit to master, we will test your changes first at the beta branch!
updated pull request template to remove mention of the beta branch
no
beta removal discussed in #8 
> updated pull request template to remove mention of the beta branch

- libsrc/hyperion/CMakeLists.txt
tiny fix for serialport migration  - please merge quickly
no
no
> fix linking for serialport

- README.md
- include/effectengine/EffectEngine.h
- include/utils/Logger.h
- libsrc/effectengine/Effect.cpp
- libsrc/effectengine/Effect.h
- libsrc/effectengine/EffectEngine.cpp
- libsrc/hyperion/CMakeLists.txt
- src/hyperiond/main.cpp
- effectengine uses new logger
- hyperiond has new options to control verbosity:
```
--verbose (min level info)
--debug (min lvel debug)
--silent (logging off)
no option given: min level is Warning
```
no
#25 #24
> migrate logging for effects and verbose options

- libsrc/leddevice/LedDeviceWS281x.cpp
- libsrc/leddevice/LedDeviceWS281x.h
- libsrc/leddevice/LedUdpDevice.cpp
- libsrc/leddevice/LedUdpDevice.h
logging migration for ws281x and LedUdpDevice
> logging migration for ws281x and LedUdpDevice

- libsrc/leddevice/LedDeviceAPA102.cpp
- libsrc/leddevice/LedDevicePiBlaster.cpp
- libsrc/leddevice/LedDevicePiBlaster.h
- libsrc/leddevice/LedSpiDevice.cpp
- libsrc/leddevice/LedUdpDevice.cpp
More logging cleanup on led devices
LedUdpDevice - better error checking/logging
nope
> More logging cleanup on led devices

- include/leddevice/LedDevice.h
- libsrc/leddevice/CMakeLists.txt
- libsrc/leddevice/LedDevice.cpp
- libsrc/leddevice/LedDeviceAtmo.cpp
- libsrc/leddevice/LedDeviceFactory.cpp
- libsrc/leddevice/LedDeviceFadeCandy.cpp
- libsrc/leddevice/LedDeviceHyperionUsbasp.cpp
- libsrc/leddevice/LedDeviceLightpack-hidapi.cpp
- libsrc/leddevice/LedDevicePhilipsHue.cpp
- libsrc/leddevice/LedDevicePiBlaster.cpp
- libsrc/leddevice/LedDevicePiBlaster.h
- libsrc/leddevice/LedDeviceSedu.cpp
- libsrc/leddevice/LedDeviceUdp.cpp
- libsrc/leddevice/LedDeviceWS281x.cpp
- libsrc/leddevice/LedDeviceWS281x.h
- libsrc/leddevice/LedHIDDevice.cpp
- libsrc/leddevice/LedRs232Device.cpp
- libsrc/leddevice/LedRs232Device.h
- libsrc/leddevice/LedSpiDevice.cpp
- libsrc/leddevice/LedUdpDevice.cpp
migrate leddevices to new logger.
make a _log member avaialable throuhg LedDevice base class. This is directly usable in all led devices without getting a logger instance
still todo:
LedDeviceWS2812b
LedDeviceWs2812SPI
LedDeviceTinkerforge
LedDeviceLightpack
LedDeviceMultiLightpack
#25
> Logging leds

- include/udplistener/UDPListener.h
- libsrc/udplistener/UDPListener.cpp
- src/hyperiond/hyperiond.cpp
implement udplisitener start/stop during runtime.
@penfold42 can you check if all things go right?
> Udplistener start/stop during runtime

- libsrc/leddevice/LedDeviceUdpRaw.cpp
- libsrc/leddevice/LedDeviceUdpRaw.h
- libsrc/leddevice/LedDeviceWs2801.cpp
- libsrc/leddevice/LedDeviceWs2801.h
These are old unused constructors that i never cleaned up when I added "latchtime" to the 2801 SPI driver (and then copy/pasted when i created leddeviceudpraw)
no
> Remove unused constructors

- include/boblightserver/BoblightServer.h
- libsrc/boblightserver/BoblightClientConnection.cpp
- libsrc/boblightserver/BoblightClientConnection.h
- libsrc/boblightserver/BoblightServer.cpp
- src/hyperiond/hyperiond.cpp
as the title says: 
boblight: new logger + start/stoppable during runtime
same pattern as in udplistener used
#3 #25 
> boblight: new logger + start/stoppable during runtime

- config/hyperion.config.json.commented
- config/hyperion.config.json.default
- include/utils/Logger.h
- libsrc/utils/Logger.cpp
- src/hyperiond/hyperiond.cpp
- src/hyperiond/hyperiond.h
make log level settings avail in config file
#26
> make log level settings avail in config file

- test/TestSpi.cpp
- test/dispmanx2png/CMakeLists.txt
- test/switchPinCtrl.c
- my 2801 cleanups caused one of the tests to file.
- one of the pi tests wouldnt compile cleanly on x86_64
nope
#65 
> fixes to small test tools to compile cleanly

- libsrc/utils/ImageResampler.cpp
- libsrc/utils/RgbToRgbw.cpp
I have added the logging function to 2 files in utils.
This is my first pull request let me know if you have any issues
no
#25 
> added logging for files that were lacking it.

- src/hyperiond/hyperiond.cpp
add missing include
try to fix build
> try to fix build

- include/grabber/AmlogicGrabber.h
- include/grabber/X11Grabber.h
- libsrc/grabber/amlogic/AmlogicGrabber.cpp
- libsrc/grabber/x11/X11Grabber.cpp
I have added logging to X11Grabber files and the AmlogicGrabber files
#25 
> Added logging to X11Grabber

- libsrc/leddevice/LedDeviceFactory.cpp
- libsrc/leddevice/LedDeviceUdp.cpp
- libsrc/leddevice/LedDeviceWS2812b.cpp
Cleaned up old commented out printf statements.
The piblaster stuff probably needs to be moved out of the devicefactory but Ill have to do that later
> More logging migration.

- test/dispmanx2png/CMakeLists.txt
- test/dispmanx2png/dispmanx2png.cpp
I suspect this is Qt5 related.
nope
> Fix compile errors of tests/dispmanx2png on rpi/osmc

- src/hyperiond/main.cpp
better error output when hyperion core exits with exception
no
> catch exceptions in hyperiond

- .gitmodules
Update submodule references - rpi_ws281x to @hyperion-project fork
It looks like I also bumped the protobuf to a later commit with some cmake fixes
nope
> Update submodule references - rpi_ws281x to @hyperion-project fork

- include/grabber/DispmanxFrameGrabber.h
- include/grabber/FramebufferFrameGrabber.h
- include/grabber/OsxFrameGrabber.h
- include/grabber/V4L2Grabber.h
- libsrc/grabber/dispmanx/DispmanxFrameGrabber.cpp
- libsrc/grabber/framebuffer/FramebufferFrameGrabber.cpp
- libsrc/grabber/osx/OsxFrameGrabber.cpp
- libsrc/grabber/v4l2/V4L2Grabber.cpp
- libsrc/grabber/x11/X11Grabber.cpp
Logging for dispmanx, framebuffer, hyperion-x11, v4l2, osx
no
https://github.com/hyperion-project/hyperion.ng/issues/25
> Logging for dispmanx, framebuffer, x11, v4l2, osx

- config/hyperion.config.json.commented
- config/hyperion.config.json.default
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/LinearColorSmoothing.cpp
Migrate logging and add "enable" to smoothing
"smoothing" :
{
"enable"          : false,
"type"            : "none",
"time_ms"         : 50,
"updateFrequency" : 25.0000
}
#3 #25
> Migrate logging and add "enable" to smoothing

- libsrc/grabber/amlogic/AmlogicWrapper.cpp
- libsrc/grabber/dispmanx/DispmanxWrapper.cpp
- libsrc/protoserver/ProtoConnection.cpp
- libsrc/webconfig/CgiHandler.cpp
- libsrc/webconfig/QtHttpClientWrapper.cpp
- libsrc/webconfig/QtHttpServer.cpp
- libsrc/webconfig/StaticFileServing.cpp
- libsrc/webconfig/StaticFileServing.h
> HTTP server logging migration (and other random small cleanups)

- include/hyperion/ImageProcessor.h
- libsrc/grabber/v4l2/V4L2Grabber.cpp
- libsrc/leddevice/LedDevicePiBlaster.cpp
- src/hyperion-aml/hyperion-aml.cpp
- src/hyperion-dispmanx/hyperion-dispmanx.cpp
- src/hyperion-framebuffer/hyperion-framebuffer.cpp
- src/hyperion-osx/hyperion-osx.cpp
- src/hyperion-v4l2/hyperion-v4l2.cpp
- src/hyperion-x11/hyperion-x11.cpp
> logging migration of blackborder and grabber

- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/utils/HslTransform.cpp
Tested and works very well. So i accepted both :)
> Bugfix sync with hyperion repo

- .travis/travis_build.sh
> Travis tests

- .travis.yml
- .travis/travis_build.sh
- test/testrunner.sh
split build and test.
add test that config files matches spec and are loadable
> Testrunner

- include/utils/jsonschema/QJsonFactory.h
- include/utils/jsonschema/QJsonSchemaChecker.h
- libsrc/utils/CMakeLists.txt
- libsrc/utils/jsonschema/QJsonSchemaChecker.cpp
- test/TestConfigFile.cpp
Wie die Überschrift schon vermuten lässt. Habe den JSONSchemaChecker von JsonCPP in QT umgeschrieben. Den alten Code müssen wir leider noch bestehen lassen.
Benutzt wird der neue Code bis jetzt nur von der Testdatei "test_configfile".
> Rewrite JSONSchemaChecker to QT

- config/hyperion.config.json.commented
- config/hyperion.config.json.default
- libsrc/hyperion/hyperion.schema.json
- libsrc/leddevice/LedRs232Device.cpp
- libsrc/leddevice/LedRs232Device.h
... fix resourceerror in serialport implemention and  extend error output.
#133 #87
> fix serial port device crash

- config/hyperion.config.json.commented
- config/hyperion.config.json.default
- include/hyperion/Hyperion.h
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/hyperion.schema.json
add ability to disable specific color corrections
update protobuf external
move smoothing out of color section
new options in color section: 
transform_enable
temperature_enable
channelAdjustment_enable
see default config for details
#23
> color filter config additions

- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/jsonserver/JsonClientConnection.h
- libsrc/jsonserver/JsonSchemas.qrc
- libsrc/jsonserver/schema/schema-configget.json
- libsrc/jsonserver/schema/schema.json
- src/hyperion-remote/JsonConnection.cpp
- src/hyperion-remote/JsonConnection.h
- src/hyperion-remote/hyperion-remote.cpp
The JSON Interface return the actual loaded config file.
Send the JSON Object : {"command": "configget"} or use "hyperion-remote --configget"
no
[Hyperion V2.0 target features](https://hyperion-project.org/threads/hyperion-v2-0-target-features.171/#post-2272)
> Update Json Interface (return config file)

- include/kodivideochecker/KODIVideoChecker.h
- include/udplistener/UDPListener.h
- libsrc/kodivideochecker/KODIVideoChecker.cpp
- libsrc/udplistener/UDPListener.cpp
- src/hyperiond/hyperiond.cpp
- src/hyperiond/hyperiond.h
The following function and initialization code in "hyperiond" has been converted to QTJson.
**function**
-loadConfig
**initialization code**
-logger
-createKODIVideoChecker
-startNetworkServices
-createSystemFrameGrabber
-createGrabberX11
-createGrabberFramebuffer
-createGrabberOsx
-createGrabberV4L2
**TODO:**
-hyperion (line 54)
-startInitialEffect (function on line 191)
no
> JsonCpp to QTJson (Part 2)

- libsrc/leddevice/LedUdpDevice.cpp
- libsrc/leddevice/LedUdpDevice.h
left over unneeded spi include
variable cleanup
no
#149 
> cleanup of udp device.

- libsrc/effectengine/EffectEngine.cpp
- libsrc/leddevice/LedDeviceLightpack-hidapi.cpp
- libsrc/leddevice/LedDeviceLightpack.cpp
- libsrc/leddevice/LedDeviceMultiLightpack.cpp
updated more incorrect logging types (%s vs %d)
no
> updated more incorrect logging types (%s vs %d)

- assets/webconfig/js/app/views/MainView.js
Just a small change for the webinterface. I thought it would be nice if the input field actually shows the selected color. To illustrate:
> display the currently selected color in color

- libsrc/kodivideochecker/KODIVideoChecker.cpp
> fix #158 initial state of kodi checker

- libsrc/jsonserver/JsonClientConnection.cpp
fix uncatched exception in json message handling
#148 
> fix uncatched exception in json message handling

- include/kodivideochecker/KODIVideoChecker.h
- libsrc/kodivideochecker/KODIVideoChecker.cpp
another fix for kodi initial state. Now it should work when on startup video is playing a or menu is displayed.
> Kodi initial fix

- libsrc/webconfig/QtHttpClientWrapper.cpp
- libsrc/webconfig/StaticFileServing.cpp
fix default index.html in subfolders
fix \r\n appended to data
> webserver fix

- .gitignore
- libsrc/leddevice/LedDeviceFactory.cpp
- libsrc/leddevice/LedDeviceUdpE131.cpp
- libsrc/leddevice/LedDeviceUdpE131.h
Add support for > 170 leds. These are send as multiple packets
Change default latchtime to be smaller
more code tidying
added *.swp to gitignore
nope
> support > 170 leds with E1.31

- include/grabber/X11Grabber.h
- libsrc/grabber/x11/X11Grabber.cpp
Faster Image scaling by XRender.
Please see Issue on old hyperion Thread for Details.
Many thanks to oCanna for his Work.
no
[hyperion-x11 grabber speed-up suggestion ](https://github.com/hyperion-project/hyperion/issues/722)
> Update X11 Grabber (scaling improvements)

- libsrc/grabber/x11/X11Grabber.cpp
- libsrc/utils/ImageResampler.cpp
Sorry for that. After code testing, i have overlook this.
no
Nach dem testen des Codes, leider übersehen und nicht rückgängig gemacht.
Entschuldigung.
> Fix "if" statement in XShmGetImage check and other things

- assets/webconfig/content/grabber.html
- assets/webconfig/content/leds.html
- assets/webconfig/js/content_grabber.js
- assets/webconfig/js/content_index.js
- assets/webconfig/js/content_leds.js
- include/leddevice/LedDevice.h
- libsrc/hyperion/hyperion.schema.json
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/leddevice/LedDevice.cpp
- libsrc/leddevice/LedDeviceSchemas.qrc
- libsrc/leddevice/LedDeviceSk6812SPI.cpp
- libsrc/leddevice/schemas/schema-e131.json
- libsrc/leddevice/schemas/schema-fadecandy.json
- libsrc/leddevice/schemas/schema-file.json
- libsrc/leddevice/schemas/schema-philipshue.json
- libsrc/leddevice/schemas/schema-udpraw.json
initial support for leddevice options (no writing, only display fields and default values)
(note: for writing the json from editor, we have to merge the jsons for general and specific ledoptions in js code)
fix leddevice schemas
> webui: initial support for leddevice options

- libsrc/leddevice/LedDeviceAdalight.cpp
- libsrc/leddevice/LedDeviceAdalightApa102.cpp
Debug level logging will now include:
```
[HYPERIOND LedDevice] <DEBUG> <LedDeviceAdalight.cpp:52:write()> Adalight header for 316 leds: Ada 0x01 0x3b 0x6f
```
nope
#227 
> Added debug logging of the Ada header bytes that are sent

- CODING_STYLE.md
- libsrc/leddevice/LedDeviceTpm2net.cpp
- libsrc/leddevice/LedDeviceTpm2net.h
- libsrc/leddevice/LedDeviceUdpE131.cpp
- libsrc/leddevice/LedDeviceUdpE131.h
- libsrc/leddevice/LedDeviceUdpRaw.cpp
- libsrc/leddevice/LedDeviceUdpRaw.h
- libsrc/leddevice/ProviderUdp.cpp
- libsrc/leddevice/ProviderUdp.h
- libsrc/leddevice/schemas/schema-e131.json
- libsrc/leddevice/schemas/schema-tpm2net.json
- libsrc/leddevice/schemas/schema-udpraw.json
add ability for default values in providerudp
extend/fix udp ledevice schema files
add default port for tpm2net according http://www.ledstyles.de/ftopic18969.html
move switchOff into baseclass
no
> add ability for default values in providerudp

- include/blackborder/BlackBorderProcessor.h
- include/hyperion/Hyperion.h
- include/hyperion/ImageProcessor.h
- include/hyperion/ImageProcessorFactory.h
- include/hyperion/LedString.h
- libsrc/blackborder/BlackBorderProcessor.cpp
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/ImageProcessor.cpp
- libsrc/hyperion/ImageProcessorFactory.cpp
- src/hyperiond/hyperiond.cpp
- test/TestBlackBorderProcessor.cpp
- test/TestImage2LedsMap.cpp
In German only.
Ja, was soll ich schreiben? Keine gravierenden Erneuerungen im Quellcode.
Den ganzen "MultiColorAdjustmentTemperaturTransformCorrection..." Code auf QT Json umgeschrieben sowie ein bisschen Blackborder und ImageProcessor angepasst. ;-)
Was bleibt noch übrig?
-EffectEngine
-LedDeviceFactory
-JsonClientConnection
No
[use qt5 json #31](https://github.com/hyperion-project/hyperion.ng/issues/31#issuecomment-248965831)
> JsonCpp to QTJson (Part 3)

- libsrc/leddevice/CMakeLists.txt
- libsrc/leddevice/LedDeviceDMX.cpp
- libsrc/leddevice/LedDeviceDMX.h
- libsrc/leddevice/LedDeviceFactory.cpp
- libsrc/leddevice/LedDeviceSchemas.qrc
- libsrc/leddevice/ProviderRs232.cpp
- libsrc/leddevice/ProviderRs232.h
- libsrc/leddevice/schemas/schema-dmx.json
Add DMX512/Rs232 support
```
"device" :
{
"name"       : "DefaultHyperionConfig",
"type"       : "dmx",
"output"        : "/dev/ttyUSB0",
"rate"  : 250000,
"colorOrder" : "grb"
},
```
> Dmx512 Rs232 support

- libsrc/webconfig/StaticFileServing.cpp
Added avahi/bonjour advertisement to webconfig
nope
> Added avahi/bonjour advertisement to webconfig

- assets/firmware/arduino/adalight/adalight.ino
this is suitable for latest tag. see here: https://github.com/FastLED/FastLED/blob/v3.1.3/FastLED.h
> update led devices in adalight sketch

- libsrc/leddevice/LedDeviceHyperionUsbasp.h
- libsrc/leddevice/LedDevicePiBlaster.h
- libsrc/leddevice/LedDeviceSk6812SPI.h
- libsrc/leddevice/LedDeviceTpm2net.h
- libsrc/leddevice/LedDeviceWS2812b.h
- libsrc/leddevice/LedDeviceWS281x.h
- libsrc/leddevice/LedDeviceWs2812SPI.h
- libsrc/leddevice/ProviderUdp.h
> Updated comments in led device headers

- assets/webconfig/content/colors.html
- assets/webconfig/content/effects.html
- assets/webconfig/content/grabber.html
- assets/webconfig/content/kodiconf.html
- assets/webconfig/content/network.html
- assets/webconfig/index.html
- assets/webconfig/js/content_colors.js
- assets/webconfig/js/content_effects.js
- assets/webconfig/js/content_generalconf.js
- assets/webconfig/js/content_grabber.js
- assets/webconfig/js/content_index.js
- assets/webconfig/js/content_kodi.js
- assets/webconfig/js/content_leds.js
- assets/webconfig/js/content_network.js
- assets/webconfig/js/ui_utils.js
- libsrc/hyperion/hyperion.schema.json
- libsrc/utils/jsonschema/QJsonSchemaChecker.cpp
implement a function for easy json editor creation
> implement a function for easy json editor creation

- include/effectengine/ActiveEffectDefinition.h
- include/effectengine/EffectDefinition.h
- include/effectengine/EffectEngine.h
- include/hyperion/Hyperion.h
- include/leddevice/LedDevice.h
- include/utils/jsonschema/QJsonFactory.h
- include/utils/jsonschema/QJsonSchemaChecker.h
- libsrc/effectengine/Effect.cpp
- libsrc/effectengine/Effect.h
- libsrc/effectengine/EffectEngine.cpp
- libsrc/hyperion/Hyperion.cpp
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/jsonserver/JsonClientConnection.h
- libsrc/jsonserver/schema/schema-config.json
- libsrc/leddevice/LedDevice.cpp
- libsrc/utils/jsonschema/QJsonSchemaChecker.cpp
- src/hyperion-remote/JsonConnection.cpp
- src/hyperion-remote/JsonConnection.h
- src/hyperion-remote/hyperion-remote.cpp
- src/hyperiond/hyperiond.cpp
In German only.
Was wurde von JsonCPP auf QTJson umgeschrieben?
- Die komplette EffectEngine.
- Die komplette JsonClientConnection.
- Ein kleiner Teil der LEDDevice.
- Der InitialEffect Bereich im Hyperion Deamon
- Hyperion-Remote wurde angepasst
Eine Randnotiz: Der Json Writer (über)schreibt ab diesem PR nur noch die komplette Hyperion Config.
Was bleibt noch übrig?
- Hyperion-Remote
- LedDevices
- WebConfig
- TestSPI
> JsonCpp to QTJson (Part 4)

- assets/webconfig/content/colors.html
- assets/webconfig/content/effects.html
- assets/webconfig/content/grabber.html
- assets/webconfig/content/kodiconf.html
- assets/webconfig/content/network.html
- assets/webconfig/js/content_colors.js
- assets/webconfig/js/content_effects.js
- assets/webconfig/js/content_grabber.js
- assets/webconfig/js/content_index.js
- assets/webconfig/js/content_kodi.js
- assets/webconfig/js/content_leds.js
- assets/webconfig/js/content_network.js
- assets/webconfig/js/ui_utils.js
as the title said .. add read/write for all editors in webui.
Now you we can write all values (except log and webui - I decided that are 'nerd' settings and they can only be set in config manually)
when trying out, please backup your config before!!! (just some precautions ... )
no
> webui: add read/write for all editors

- bin/openelec/hyperiond.sh
- bin/service/hyperion.systemd.OE.LE.sh
- bin/service/hyperion.systemd.sh
- cmake/debian/postinst
- include/utils/FileUtils.h
- libsrc/utils/FileUtils.cpp
- libsrc/utils/Logger.cpp
- libsrc/utils/Profiler.cpp
- src/hyperiond/main.cpp
when starting hyperiond like:
`./hyperiond myconfig.json`
and "myconfig.json" doesn't exists, the the default config will be written. After that you can call from browser http://your_hyperion_ip:8099 to set the real values in config. (except setup of led layout, this is still in progress)
you can also try this
`./hyperiond conf/myconfig.json`
then directory "conf" containing "myconfig.json" will be created.
The Idea is, that we can start without an existing config and then configure it via webui.
additionals:
I had to remove of multiple hyperion instance creation. This function will be reimplemented in that way:  #55
rename hyperion service in debian package to hyperiond ( #86 )
I also tweak the systemd files a bit ...
**2.** If this changes …
> auto generation of initial config file

- src/hyperion-remote/hyperion-remote.cpp
> hyperion-remote help screen needs "--blah" not "-blah" for the long options

- include/effectengine/EffectEngine.h
- include/hyperion/Hyperion.h
- libsrc/effectengine/EffectEngine.cpp
- libsrc/hyperion/Hyperion.cpp
- libsrc/jsonserver/JsonClientConnection.cpp
Nothing to say. See Description or Code for Details. :-)
no
> Implement "reloadEffects" function in Hyperion for "write and delete" custom created effect configuration files

- effects/strobe-blue.json
- effects/strobe-raspbmc.json
- effects/strobe-white.json
- effects/strobe.py
The strobe effect miscalculated the frequency
no, but the strobe effects will now run twice as quickly.
I've also ammended the default effects to suit
> fix strobe effect frequency

- libsrc/leddevice/LedDeviceSchemas.qrc
- libsrc/leddevice/LedDeviceSk6812SPI.cpp
- libsrc/leddevice/LedDeviceSk6812SPI.h
- libsrc/leddevice/LedDeviceWs2812SPI.cpp
- libsrc/leddevice/LedDeviceWs2812SPI.h
- libsrc/leddevice/schemas/schema-sk6812spi.json
- libsrc/leddevice/schemas/schema-ws2812spi.json
- libsrc/leddevice/schemas/schema-ws281x.json
sk6812SPI was buggy
cleaned up code - make sk6812spi and ws2812spi more consistent
led device schema updates
> led device cleanup, bug fix and schemas

- effects/knight-rider.py
- effects/mood-blobs.py
- effects/police.py
- effects/rainbow-mood.py
- effects/rainbow-swirl.py
- effects/x-mas.py
- libsrc/jsonserver/JsonClientConnection.cpp
- src/hyperiond/main.cpp
this fixes bug:
1. start hyperion
2. open webui
3. open e.g. led config
4. change config file on disk (e.g. device -> name)
prior: in webui always old value is displayed in webui, until restart
now:  in webui always current value is displayed
> always output latest version of config file to webui

- assets/firmware/arduino/adalight/adalight.ino
some code tweaks for adalight firmware
> optimize adalight firmware

- libsrc/leddevice/LedDeviceLpd6803.cpp
- libsrc/leddevice/LedDeviceLpd8806.cpp
fix for LPD8806 issue - wrong number of bytes sent on setup
make writebytes call consistent with other devices
no
#204 
> fix for LPD8806 issue

- libsrc/leddevice/LedDevicePhilipsHue.cpp
> Added missing json document compilation to states retrieval.

- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/jsonserver/JsonClientConnection.h
See Description Title or Code for changes.
no
> Overwrite custom created effect config when effect name is exist

- libsrc/hyperion/hyperion.schema.json
iOS app needs this (at the moment) and i needs to be able to set the inital config from the config file.
```
"transform" :
[
{
"id"   : "default",
"leds" : "*",
"hsv" :
{
"saturationGain"   : 1.0000,
"valueGain"    : 0.1000
},
```
I need it!! thats an issue *grin*
> Re-introduce hsv transform into config schema.

- assets/webconfig/js/content_logging.js
- libsrc/jsonserver/JsonClientConnection.cpp
The WebUI Logger output is equal to console output
no
> Logger output in WebUI

- assets/webconfig/content/leds.html
- assets/webconfig/i18n/de.json
- assets/webconfig/i18n/en.json
- assets/webconfig/js/content_leds.js
- assets/webconfig/js/hyperion.js
- assets/webconfig/js/ui_utils.js
- include/hyperion/Hyperion.h
- libsrc/grabber/v4l2/V4L2Wrapper.cpp
- libsrc/grabber/x11/X11Wrapper.cpp
- libsrc/hyperion/GrabberWrapper.cpp
- libsrc/hyperion/Hyperion.cpp
- libsrc/jsonserver/CMakeLists.txt
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/jsonserver/JsonClientConnection.h
- src/hyperiond/hyperiond.cpp
shown is the image after image processing. That means it is shrinked and looks a bit old fashioned ;-)
Update intervall is reduced to 4Hz ... we can increase, but it is not necessary to spam the lan.
here a picture:
#320 
> implement webui live video

- include/hyperion/Hyperion.h
- include/hyperion/ImageProcessor.h
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/ImageProcessor.cpp
- libsrc/jsonserver/JsonClientConnection.cpp
> implement states for components_autoselect and ledMAppingType via json

- effects/trails.json
- effects/trails.py
- effects/trails_color.json
> Trails effect

- CMakeLists.txt
- libsrc/hyperion/schemas/hyperion.schema-2.json
- libsrc/protoserver/ProtoClientConnection.cpp
.. and add clean of qrc on make clean
> implement adjustable image2ledmaptype for proto

- libsrc/protoserver/ProtoClientConnection.cpp
make video from proto available in webui live view
> make video from proto available in webui live view

- libsrc/hyperion/Hyperion.cpp
> fix state of autoselect

- config/hyperion.config.json.commented
- config/hyperion.config.json.default
- include/hyperion/Hyperion.h
- include/utils/Components.h
- include/utils/Logger.h
- include/utils/RgbChannelAdjustment.h
- libsrc/grabber/v4l2/V4L2Grabber.cpp
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/MultiColorAdjustment.cpp
- libsrc/hyperion/MultiColorAdjustment.h
- libsrc/hyperion/PriorityMuxer.cpp
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/utils/Logger.cpp
- libsrc/utils/RgbChannelAdjustment.cpp
- src/hyperion-remote/JsonConnection.cpp
- fix coloradjustment via hyperion remote
- several small cleanups/refactorings
- set brighness to 0.75 This should be a faire compromise between not to bright, but more color dynamics ...
>  fix coloradjustment via hyperion remote

- assets/webconfig/i18n/de.json
- assets/webconfig/i18n/en.json
- assets/webconfig/index.html
- assets/webconfig/js/hyperion.js
- libsrc/hyperion/Hyperion.cpp
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/jsonserver/JsonClientConnection.h
- libsrc/jsonserver/schema/schema-config.json
- libsrc/webconfig/CgiHandler.cpp
- libsrc/webconfig/CgiHandler.h
- libsrc/webconfig/QtHttpClientWrapper.cpp
- libsrc/webconfig/QtHttpReply.h
- libsrc/webconfig/QtHttpRequest.cpp
- libsrc/webconfig/QtHttpRequest.h
- libsrc/webconfig/QtHttpServer.cpp
- libsrc/webconfig/QtHttpServer.h
- libsrc/webconfig/StaticFileServing.cpp
- use http post to transmit the config from webui to hyperion
- update webserver code
- remove obsolete code for multicoloradjustment
now saving config should work as expected. A todo is the connection lost detection, this can lead to false connection lost messages (e.g. when network/device is slow)
> move write config from json api to http post 

- include/grabber/DispmanxWrapper.h
- include/hyperion/GrabberWrapper.h
- libsrc/grabber/dispmanx/DispmanxWrapper.cpp
- libsrc/hyperion/GrabberWrapper.cpp
> remove obsolete kodi code for grabbers

- assets/firmware/arduino/adalight/adalight.ino
- assets/firmware/arduino/network_bridge/udpraw_serialadalight.py
- NUM_LEDS becomes MAX_LEDS and any led data beyond that is ignored
Added a python udp listener and serial sender.
- Intended for windows users with a COM port based led strip.
- Works with hyperion
> Updated adalight sketch to use the number of leds sent in the header

- libsrc/webconfig/StaticFileServing.cpp
- this is a quick hack, should be refactored later
@brindosh pleas test if this fit your needs, if so please merge it.
> implement 404 for webserver

- include/utils/jsonschema/QJsonFactory.h
- include/utils/jsonschema/QJsonSchemaChecker.h
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/utils/jsonschema/QJsonSchemaChecker.cpp
- libsrc/webconfig/WebConfig.cpp
- src/hyperiond/hyperiond.cpp
- test/TestConfigFile.cpp
> Remove duplicated Code

- assets/firmware/arduino/adalight/adalight.ino
Updated comments about MAX_LEDS
It's hard to count past 256 with only 8 fingers...
> fixed bug limiting the sketch to 256 LEDs.

- effects/clock.json
- effects/clock.py
And another effect. Just my little contribution to make this project even more awesome.
> add clock effect

- libsrc/bonjour/CMakeLists.txt
- libsrc/effectengine/Effect.cpp
- libsrc/effectengine/Effect.h
- libsrc/leddevice/ProviderRs232.cpp
- test/jsonchecks/checkeffects.py
- test/jsonchecks/checkjson.py
- test/jsonchecks/checkschema.py
add more drawing func to effect engine:
- draw line
- drawRect
- setPixel
- getPixel
other stuff:
- make provider rs232 less noisy
- json checks: remove utf8 conversion temporarily and make it compat with py3 again
> add more drawing func to effect engine

- assets/firmware/arduino/adalight_mega_pwm/hyperion_mega.ino
- include/boblightserver/BoblightServer.h
- include/effectengine/EffectEngine.h
- include/hyperion/Hyperion.h
- include/udplistener/UDPListener.h
- include/utils/Components.h
- include/utils/Logger.h
- include/utils/global_defines.h
- libsrc/boblightserver/BoblightClientConnection.cpp
- libsrc/boblightserver/BoblightClientConnection.h
- libsrc/effectengine/Effect.cpp
- libsrc/effectengine/Effect.h
- libsrc/effectengine/EffectEngine.cpp
- libsrc/hyperion/GrabberWrapper.cpp
- libsrc/hyperion/Hyperion.cpp
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/jsonserver/JsonClientConnection.h
- libsrc/jsonserver/schema/schema-image.json
- libsrc/protoserver/ProtoClientConnection.cpp
- libsrc/protoserver/ProtoClientConnection.h
- libsrc/udplistener/UDPListener.cpp
- libsrc/utils/CMakeLists.txt
- libsrc/utils/Logger.cpp
- src/hyperion-remote/JsonConnection.cpp
- implement "origin" for effects
- fix/add origin for network services
- fix log buffer QT signaling
- add experimental adalight  firmware for arduino mega (with upto 5 rgb pwm channles + 1 addressable led stripe)
- more conversion of STL types to QT types (mainly std::string to QString)
no
#349 
> implement origin for effects 

- assets/webconfig/i18n/de.json
- assets/webconfig/i18n/en.json
- assets/webconfig/i18n/es.json
- config/hyperion.config.json.commented
- config/hyperion.config.json.default
- include/grabber/V4L2Grabber.h
- include/grabber/V4L2Wrapper.h
- libsrc/grabber/v4l2/V4L2Grabber.cpp
- libsrc/grabber/v4l2/V4L2Wrapper.cpp
- libsrc/hyperion/schemas/hyperion.schema-2.json
- src/hyperion-v4l2/hyperion-v4l2.cpp
- src/hyperiond/hyperiond.cpp
...
new option "signalDtetection"
> make v4l signal detection switchable

- include/bonjour/bonjourrecord.h
- libsrc/bonjour/bonjourservicebrowser.cpp
- libsrc/hyperion/Hyperion.cpp
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/webconfig/StaticFileServing.cpp
- libsrc/webconfig/WebConfig.cpp
- src/hyperiond/hyperiond.cpp
- add ip
- make dns service names more uniq (important for multiple local instances)
```
"hyperion": {
"config_modified": false,
"config_writeable": true,
"sessions": [
{
"address": "192.168.122.1",
"domain": "local.",
"host": "dory",
"name": "MyHyperionConfig@dory:8098",
"port": 8098,
"type": "_hyperiond-http._tcp."
},
{
"address": "192.168.122.1",
"domain": "local.",
"host": "dory",
"name": "MyPi@dory:8099",
"port": 8099,
"type": "_hyperiond-http._tcp."
}
]
},
```
> zeroconf updates

- include/utils/RgbChannelAdjustment.h
- libsrc/hyperion/MultiColorAdjustment.cpp
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/utils/RgbChannelAdjustment.cpp
... do some housework - now settings color adjustment at runtime is less calculation intensive and don't do unnecessary things.
> cleanup color adjustment

- CompileHowto.md
updated cp command, otherwise /opt/opt/... will be created...
> updated command for raspberry

- libsrc/leddevice/LedDeviceWs2812SPI.cpp
- libsrc/leddevice/LedDeviceWs2812SPI.h
Ammeded timing to suit new revision of ws2812c
Should also work with WS2813 (but untested)
Included comments on the timing calculations
nope
#437 
> Ammeded timing to suit new revision of ws2812c

- .gitmodules
- assets/webconfig/i18n/de.json
- assets/webconfig/i18n/en.json
- assets/webconfig/i18n/es.json
- dependencies/CMakeLists.txt
- libsrc/leddevice/LedDeviceWS281x.cpp
- libsrc/leddevice/schemas/schema-ws281x.json
Update submodule and added DMA  channel to schema
See schema
> Rpi ws281x submodule update

- CompileHowto.md
- libsrc/leddevice/LedDevicePiBlaster.cpp
Fixed piblaster support
and added "sudo" to the CompileHowto
nope
> Fixed piblaster support

- include/leddevice/LedDevice.h
- libsrc/leddevice/LedDevice.cpp
- libsrc/leddevice/dev_net/LedDevicePhilipsHue.cpp
- libsrc/leddevice/dev_net/LedDevicePhilipsHue.h
- libsrc/leddevice/schemas/schema-philipshue.json
This is a patched, rewriten and improved version of the philiphs hue implementation
Changes:
- segfaults segfault segfaults. No segfaults! Solid against wrong configuration, bridge not reachable, unknown light ids and so on
- No thread freezers anymore which leads to unexpected behaviour like closed sockets or not responding sockets of the hyperion api
- check if bridge is reachable, user has access
- latchTime auto adjusted based on configured lightIDs
- switchOffOnBlack working again
- compatible with led device component on/off
- more logging what's actually going on
- lightID detection should be better, i hope that all bridges supports this (update to recent firmware to be save)
- 2 new lamp models added
@ntim 
xy == CiColor::BLACK -> rgb …
> Philiphs Hue Improvments

- CMakeLists.txt
- CompileHowto.md
- libsrc/effectengine/CMakeLists.txt
- libsrc/hyperion/CMakeLists.txt
- libsrc/leddevice/CMakeLists.txt
- libsrc/utils/CMakeLists.txt
- libsrc/webconfig/CMakeLists.txt
- src/hyperion-aml/CMakeLists.txt
- src/hyperion-dispmanx/CMakeLists.txt
- src/hyperion-framebuffer/CMakeLists.txt
- src/hyperion-osx/CMakeLists.txt
- src/hyperion-remote/CMakeLists.txt
- src/hyperion-v4l2/CMakeLists.txt
- src/hyperion-x11/CMakeLists.txt
- Migrate to cmake 3.0.0
- Special compile note for Ubuntu 14.04
Reason: https://github.com/hyperion-project/hyperion.ng/pull/479
> CMake 3.0.0

- assets/webconfig/js/content_leds.js
- libsrc/leddevice/LedDeviceSchemas.qrc
- libsrc/leddevice/dev_serial/LedDeviceKarate.cpp
- libsrc/leddevice/dev_serial/LedDeviceKarate.h
- libsrc/leddevice/schemas/schema-karate.json
Using 
https://hyperion-project.org/threads/configuration-for-karatelight.571/
as a start, this is working on my Raspberry PI with a 16 Channel Karatelight attached.
> Add Karatelight support

- libsrc/grabber/x11/X11Grabber.cpp
- src/hyperion-x11/X11Wrapper.cpp
The screen and output image resolution don't need to be updated on every frame/grab.
> Update screen dimensions only if they really change

- libsrc/leddevice/dev_net/LedDeviceAurora.cpp
- libsrc/leddevice/dev_net/LedDeviceAurora.h
Add support for Nanoleaf Aurora
Instructions to create Auth key is in http://forum.nanoleaf.me/docs/openapi under Authorization
using REST or https://github.com/software-2/nanoleaf
Example Device Config
// DEVICE CONFIGURATION 
"device" :
{
"name"       : "UDP",
"type"       : "aurora",
"output"     : "192.168.0.212",
"key"     	 : "QGitEGXKPpzndanzo1GwXgrdhxUTSuGq",
"colorOrder" : "rgb"
}
// Set number of leds equal to the number of panels
> Nanoleaf Aurora integration for Hyperion

- libsrc/leddevice/schemas/schema-aurora.json
Added schema as requested in [https://github.com/hyperion-project/hyperion.ng/pull/500](https://github.com/hyperion-project/hyperion.ng/pull/500)
> Add Schema

- README.md
I know. We could have taken this PR into another. Just for the information of everyone else
definitely not
None
> Travis Master check more visible

- assets/webconfig/i18n/de.json
- assets/webconfig/i18n/en.json
- config/hyperion.config.json.commented
- config/hyperion.config.json.default
- include/grabber/AmlogicGrabber.h
- include/grabber/AmlogicWrapper.h
- libsrc/grabber/amlogic/AmlogicGrabber.cpp
- libsrc/grabber/amlogic/AmlogicWrapper.cpp
- libsrc/grabber/amlogic/Amvideocap.h
- libsrc/hyperion/schema/schema-framegrabber.json
- libsrc/utils/ImageResampler.cpp
- src/hyperion-aml/AmlogicWrapper.cpp
- src/hyperion-aml/AmlogicWrapper.h
- src/hyperion-aml/hyperion-aml.cpp
- src/hyperiond/hyperiond.cpp
- src/hyperiond/hyperiond.h
fix ge2d mode
added ge2d single/combined ioctl call
speed up imageresampler
speed up amvideocap0 mode
added config to choose if amvideocap0 or ge2d grabber should be used
> Amlogic Grabber fix/upgrade

- libsrc/grabber/amlogic/AmlogicGrabber.cpp
fixup for https://github.com/hyperion-project/hyperion.ng/commit/499d4cb33c9702d33687e628a5bc43eb7cb88f51
none
none
> Amlogic grabber: fixup closing video device on each frame

- bin/scripts/docker-compile.sh
Changed path to docker image according to #553
> Bugfix of #553

- .travis/travis_build.sh
The package creation is currently not needed.
Should accelerate the build time in travis.
No
#560
> Travis fix

- 3RD_PARTY_LICENSES
- assets/webconfig/content/about.html
- assets/webconfig/i18n/de.json
- assets/webconfig/i18n/en.json
I have added a 3rd party license file for correct license handling. Also I linked to this file in the webui. This should be enough. 
I would like to encourage everyone to edit this file if something is missing or if you add something new. 
> Added 3rd party licenses file

- assets/webconfig/js/content_leds.js
Correct device name list overwritten by old version in PR567.
> Correct device name list

- assets/webconfig/js/content_general.js
- assets/webconfig/js/hyperion.js
- src/hyperion-remote/JsonConnection.cpp
- src/hyperion-remote/JsonConnection.h
- src/hyperion-remote/hyperion-remote.cpp
- Adds a new command to hyperion-remote that allows the selection of a instance by name
- Fixed broken umlauts
- Fixed wrong text placement inside icon tags
> Add hyperion-remote instance cmd

- include/db/SettingsTable.h
- include/ssdp/SSDPHandler.h
- include/ssdp/SSDPServer.h
- libsrc/ssdp/SSDPHandler.cpp
- libsrc/ssdp/SSDPServer.cpp
- Fix: Windows 7 network overview no longer removes the Hyperion entry
- Fix: The general section should be marked as global (Noticed: Help text option is not in sync across instances)
> Fix: SSDP Server spec adjust

- include/ssdp/SSDPDiscover.h
- include/ssdp/SSDPHandler.h
- include/ssdp/SSDPServer.h
- libsrc/ssdp/SSDPDiscover.cpp
- libsrc/ssdp/SSDPHandler.cpp
- libsrc/ssdp/SSDPServer.cpp
- src/hyperion-aml/hyperion-aml.cpp
- src/hyperion-dispmanx/hyperion-dispmanx.cpp
- src/hyperion-framebuffer/hyperion-framebuffer.cpp
- src/hyperion-osx/hyperion-osx.cpp
- src/hyperion-qt/hyperion-qt.cpp
- src/hyperion-remote/CMakeLists.txt
- src/hyperion-remote/hyperion-remote.cpp
- src/hyperion-v4l2/hyperion-v4l2.cpp
- src/hyperion-x11/hyperion-x11.cpp
- src/hyperiond/hyperiond.cpp
- src/hyperiond/main.cpp
- Feat: SSDP discovery for hyperion-remote
- Feat: Show a log msg of current user data directory
- Fix: All standalone binaries skip now properly  SSDP, when a target address is provided that differs from default
- Other: Some tiny refactor
@b1rdhous3 
So, schnell nachgereicht zur Geisterstunde :)
> Feat: SSDP discovery for hyperion-remote

- libsrc/grabber/v4l2/V4L2Grabber.cpp
The V4L2 video standards were not applied and the maximum device resolution were not used.
No
#600 & https://hyperion-project.org/threads/hyperion-ng-auf-raspberry-4-raspbian-buster-usb-grabber.3689/#post-15774
> V4L2 Grabber fixes

- 3RD_PARTY_LICENSES
> Update 3rd party license (roboto font)

- CrossCompileHowto.txt
- README.md
> Fixed Typo

- libsrc/effectengine/Effect.cpp
Fix compilation with python 3.8
#646
> fix python38 compilation

- include/hyperion/Hyperion.h
- include/hyperion/PriorityMuxer.h
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/PriorityMuxer.cpp
- fix: Backlight/BBDetector during effects
Fixes: #674
> fix: Backlight/BBDetector during effects

- .github/PULL_REQUEST_TEMPLATE.md
- libsrc/hyperion/LinearColorSmoothing.cpp
**Summary**
Smoothing was initialized as disabled, but the component state register assume on startup a disabled component. The component register was therefore out of sync
Fixes: #680
> fix: Smoothing comp state on startup

- .azure.yml
**Summary**
Add a title to Github Release
> chore: Add Azure Github release title

- src/hyperiond/CMakeLists.txt
**Summary**
The OpenSSL symlink was not resolved, which means that the library was not copied into the packages.
The Avaha library was also removed from the system list of ignored files.
Fixes: #688
> Resolved SSL/Avahi problem in Packages

- bin/compile.sh
**Summary**
Added SSL development package to bin/compile.sh
> Added SSL development package to bin/compile.sh

- assets/webconfig/js/content_dashboard.js
**Summary**
Deleted active debugger in JS. Ups, I am Sorry!
> BugFix: Deleted active debugger;

- .github/workflows/pull-request.yml
**Summary**
_The title says it all. :smile:_ 
CI/CD related thing
screen:
> GitHub Actions bot comment on PR to find artifacts faster

- CompileHowto.md
> Add libssl-dev to dependancies in build instructions

- include/grabber/V4L2Grabber.h
- include/grabber/V4L2Wrapper.h
- include/hyperion/Grabber.h
- include/hyperion/GrabberWrapper.h
- include/utils/GlobalSignals.h
- libsrc/grabber/qt/QtGrabber.cpp
- libsrc/grabber/v4l2/V4L2Grabber.cpp
- libsrc/grabber/v4l2/V4L2Wrapper.cpp
- libsrc/hyperion/CaptureCont.cpp
- libsrc/hyperion/ComponentRegister.cpp
- libsrc/hyperion/GrabberWrapper.cpp
- src/hyperiond/hyperiond.cpp
**Summary**
Listener state tracking for the enable state of capture implementations
> fix: Resolve enable state for v4l and screen capture

- include/hyperion/HyperionIManager.h
- libsrc/hyperion/HyperionIManager.cpp
- src/hyperiond/main.cpp
**Summary**
short: Re-Implemented user defined signals SIGUSR1 and SIGUSR2.
long: https://discourse.coreelec.org/t/hyperion-ng-amlogic-improvements/5476/106?u=paulchen-panther
> SIGUSR implemented again

- include/utils/hyperion.h
- libsrc/hyperion/schema/schema-color.json
**Summary**
- Prevent a heavy malformed image for effects & size is limited to 80px (performance concerns)
- Show brightness compensation of default lvl and set to initial 0 for new setups
Closes #743
Closes #741
> fix: GridSize change, show brightness compensation

- .azure.yml
**Summary**
On March 27th, 2020 Azure finished the release creation before all releases were created. In order not to repeat this scenario, I restructured the pipeline. If not all artifacts have been created, the upload to GitHub will not start. From now on, all artifacts will be uploaded to GitHub at the same time. This reduces the risk of nonexistent releases.
To avoid wasting your time, it's best to …
> Azure refactor

- libsrc/ssdp/SSDPDiscover.cpp
**Summary**
Fix addresses #726
> Fix SSDP Discovery reliability

- effects/fade.py
- effects/random.py
- effects/swirl.py
- effects/traces.py
**Summary**
Fix #757, set sleeptime to 1ms rather than 1s, if latchtime=0.
Fix #757
> Fix #757 - Some effects are running extreme slowly.

- assets/webconfig/css/darkMode.css
- assets/webconfig/css/darkModeBlack.css
**Summary**
I love the dark mode on Mac and the new option in hyperion.ng (thanks to @b1rdhous3 !!! #752 ), but the current theme in dark mode was a bit too dark for my opinion ;) So I took the time to redesign a new dark gray version for more eye care ;). Maybe we could add more dark + light themes and a theme changer (CSS file) so that the user can choose his own favorite, since this is always in the eye of the beholder ... 
The original dark black version is included as a new CSS file.
Hope you like it ...Happy Eastern!!! :D
before:
after:
...a few adjustments may still be necessary here and there...
**Does this PR introduce a …
> new dark mode - dark gray - color theme + backup previous version

- assets/webconfig/js/content_grabber.js
**Summary**
Do not render v4l2 stuff if the server has no v4l2
Closes: #777 
Relates also to: #738
> fix(webui): hide v4l2 if not available

- docs/docs/en/effects/OurFirstEffect.md
This could confuse people who does stupid copy paste 😄
**Summary**
> doc: fix small typo on effect.py

- assets/webconfig/css/darkMode.css
**Summary**
just minor darkmode css bugfixes:
- select appearance fix (missing dropdown icon)
- minor color corrections (wizard button)
before:
after:
> select appearance fix + changed wizard btn color

- docs/docs/en/user/LedDevices.md
**Summary**
First Philips Hue Entertainment API hyperion Documentation!
- [] Yes
> Philips Hue Entertainment API hyperion Documentation

- docs/docs/en/user/HyperBian.md
Simply linked to your own repo
**Summary**
> Added Link to HyperBian zip File

- libsrc/ssdp/SSDPDiscover.cpp
- libsrc/ssdp/SSDPHandler.cpp
- libsrc/ssdp/SSDPServer.cpp
**Summary**
Delay M-SEARCH response by a random value according to MX header
+
Improve some code style
> Delay M-SEARCH response by a random value according to MX header

- cmake/Dependencies.cmake
- libsrc/python/PythonInit.cpp
**Summary**
Since there is no official embedded zip from python for Linux, we simply pack the module folder into a zip file ourselves. This speeds up the unpacking process of the tar.gz archives a lot, protects SD cards since there are fewer files to write to and the number of the entire files in the archive or in the deb package decreases massively.
The loading of the python module zip file also works under Linux.
If adding a **new feature**, the PR's description …
> Embedded python package (zip) for Linux

- libsrc/webserver/CgiHandler.cpp
- libsrc/webserver/CgiHandler.h
- libsrc/webserver/StaticFileServing.cpp
**Summary**
Title says it.
Exception thrown at 0x00007FFC23F5A799 in hyperiond.exe: Microsoft C++ exception: int at memory location 0x00000009DF9FB390.
Exception thrown at 0x00007FFC23F5A799 in hyperiond.exe: Microsoft C++ exception: int at memory location 0x00000009DF9FB390.
Exception thrown at 0x00007FFC23F5A799 in hyperiond.exe: Microsoft C++ exception: int at memory location 0x00000009DF9FB390.
Exception thrown at 0x00007FFC23F5A799 in hyperiond.exe: Microsoft C++ exception: int at memory location 0x00000009DF9FB390.
Exception thrown at 0x00007FFC23F5A799 in hyperiond.exe: Microsoft C++ exception: int at memory location 0x00000009DF9FB390.
Exception thrown at 0x00007FFC23F5A799 in hyperiond.exe: Microsoft C++ exception: int at memory location 0x00000009DF9FB390.
Exception thrown at …
> Don't use exceptions as part of normal flow

- dependencies/CMakeLists.txt
- include/flatbufserver/FlatBufferConnection.h
- libsrc/flatbufserver/FlatBufferConnection.cpp
**Summary**
Changed files are recompiled at every build due to generated flat buffer headers. Use forward declaration to reduce the time spent while compiling those.
> Decrease compile time

- cmake/Findmbedtls.cmake
> Fixes: #883 -DUSE_SYSTEM_MBEDTLS_LIBS=ON - undefined reference

- assets/webconfig/js/content_logging.js
- include/utils/Image.h
- include/utils/ImageData.h
- include/utils/Logger.h
- libsrc/api/JsonAPI.cpp
- libsrc/hyperion/Hyperion.cpp
- libsrc/leddevice/dev_net/LedDeviceWled.cpp
- libsrc/ssdp/SSDPHandler.cpp
- libsrc/utils/Logger.cpp
**Summary**
Fix webui logger.
Fix random colors problem (#897)
Edit by TP:
Fixes: #913,#897
> Fix logger and led colors

- cmake/nsis/template/NSIS.template.in
- cmake/packages.cmake
- src/hyperiond/systray.cpp
- src/hyperiond/systray.h
**Summary**
The title actually says it all.
> NSIS/Systray option to launch Hyperion on Windows start [HKCU]

- .gitignore
- include/commandline/Option.h
- include/flatbufserver/FlatBufferConnection.h
- include/grabber/AmlogicWrapper.h
- include/grabber/DispmanxFrameGrabber.h
- include/grabber/DispmanxWrapper.h
- include/grabber/FramebufferFrameGrabber.h
- include/grabber/FramebufferWrapper.h
- include/grabber/OsxFrameGrabber.h
- include/grabber/OsxWrapper.h
- include/grabber/QtGrabber.h
- include/grabber/QtWrapper.h
- include/grabber/V4L2Wrapper.h
- include/grabber/X11Grabber.h
- include/grabber/X11Wrapper.h
- libsrc/commandline/ColorsOption.cpp
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/HyperionIManager.cpp
- libsrc/hyperion/SettingsManager.cpp
> Resolve some clang warnings

- include/ssdp/SSDPDiscover.h
- libsrc/ssdp/SSDPDiscover.cpp
- libsrc/utils/ImageResampler.cpp
**Summary**
Fix compiler warnings.
> Fix compiler warnings

- libsrc/utils/ImageResampler.cpp
> Get rid of unnecessary computation in ImageResampler

- CHANGELOG.md
- docs/docs/en/addons/API.md
- docs/docs/en/addons/OurFirstAddon.md
- docs/docs/en/api/Detect.md
- docs/docs/en/api/Guidelines.md
- docs/docs/en/api/Ui.md
- docs/docs/en/effects/API.md
- docs/docs/en/effects/OurFirstEffect.md
- docs/docs/en/effects/README.md
- docs/docs/en/json/Authorization.md
- docs/docs/en/json/Control.md
- docs/docs/en/json/README.md
- docs/docs/en/json/ServerInfo.md
- docs/docs/en/json/Subscribe.md
- docs/docs/en/user/Configuration.md
- docs/docs/en/user/HyperBian.md
- docs/docs/en/user/LedDevices.md
- docs/docs/en/user/advanced/Advanced.md
- docs/docs/en/user/advanced/Support.md
> Fix typos in documentation

- 3RD_PARTY_LICENSES
> Add libcec license

- bin/scripts/docker-compile.sh
Added docker pull to make sure always the latest image gets pulled from Docker Hub before starting the compile process
**Summary**
Fixes: #937 
> Added docker pull to docker-compile.sh - solves #937

- src/hyperiond/hyperiond.cpp
> Fix #971 Build without any grabber 

- CrossCompileHowto.md
**Summary**
When attempting to cross-compile, I received this error after following [the Cross Compiling Steps](https://github.com/hyperion-project/hyperion.ng/blob/master/CrossCompileHowto.md):
```
CMake Error at libsrc/grabber/xcb/CMakeLists.txt:7 (find_package):
By not providing "FindQt5X11Extras.cmake" in CMAKE_MODULE_PATH this project
has asked CMake to find a package configuration file provided by
"Qt5X11Extras", but CMake did not find one.
Could not find a package configuration file provided by "Qt5X11Extras" with
any of the following names:
Qt5X11ExtrasConfig.cmake
qt5x11extras-config.cmake
Add the installation prefix of "Qt5X11Extras" to CMAKE_PREFIX_PATH or set
"Qt5X11Extras_DIR" to a directory containing one of the above files.  If
"Qt5X11Extras" provides a separate development …
```
> Install libqt5x11extras5-dev while cross compiling

- libsrc/leddevice/dev_serial/ProviderRs232.cpp
**Summary**
Fix QRingBuffer::reserve issue as reported as part of issue #903 
Fix #903
> Fix #903 - Adalight

- libsrc/leddevice/dev_net/ProviderUdp.cpp
- libsrc/leddevice/dev_net/ProviderUdp.h
**Summary**
Improve on the error-handling and output for the UDP-Provider class.
In support of hyperion forum topic:
https://forum.hyperion-project.org/threads/new-user-trying-to-make-it-work.10643/#post-26971
**Other …
> Improve UDP-Device Error handling

- CrossCompileHowto.md
**Summary**
Updates the Linaro and QT URLs found in [CrossCompileHowto.md](https://github.com/hyperion-project/hyperion.ng/blob/master/CrossCompileHowto.md) to be the same URLs as listed before, just with their new locations, as the old ones were outdated 404s. These are the same exact downloads as before.
To avoid wasting your time, it's best to …
> Update URLs in CrossCompilingHowTo

- assets/webconfig/js/ui_utils.js
- assets/webconfig/js/wizard.js
- libsrc/leddevice/dev_net/LedDeviceYeelight.cpp
> lgtm fixes

- CHANGELOG.md
- assets/webconfig/content/about.html
- assets/webconfig/js/content_logging.js
- include/utils/SysInfo.h
- libsrc/api/JsonAPI.cpp
- libsrc/utils/SysInfo.cpp
- src/hyperiond/main.cpp
Allow to get additional information on hyperion version and CPU details.
- Provide additional details on Hardware/CPU information
- Allow execution with option "--version", while another hyperion daemon is running
The additional information is helpful during user support.
To avoid wasting your time, it's best to open a **feature request issue** …
> Additional information on system used

- README.md
- assets/webconfig/content/about.html
- assets/webconfig/content/support.html
**Summary**
I changed all visible links for the user to https. Because the author of download.js seems to abandoned the project and his site I replaced the link to the GitHub page of the project, beside working https probably a safer alternative.
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval …
> Change links from http to https

- assets/webconfig/i18n/en.json
- assets/webconfig/js/content_grabber.js
- config/hyperion.config.json.commented
- config/hyperion.config.json.default
- include/hyperion/GrabberWrapper.h
- libsrc/api/JsonAPI.cpp
- libsrc/hyperion/GrabberWrapper.cpp
- libsrc/hyperion/SettingsManager.cpp
- libsrc/hyperion/schema/schema-framegrabber.json
**Summary**
**Fix**
- Remove not supported grabber options and text
**New**
- Hide grabber types not supported
**Before Linux**
**After Linux**
> Improve Platform Grabber UI

- CHANGELOG.md
- assets/webconfig/content/about.html
- assets/webconfig/js/content_logging.js
- include/utils/SysInfo.h
- libsrc/api/JsonAPI.cpp
- libsrc/utils/CMakeLists.txt
- libsrc/utils/SysInfo.cpp
- src/hyperiond/hyperiond.cpp
- src/hyperiond/main.cpp
**Summary**
**Added**
- Provide the Qt version as part of the Server OS information shown in UI
- Provide the Python version as part of the Server OS information shown in UI
**Changed**
- Usability: Do not report unsupported features as errors for a given platform build 
To avoid wasting your time, it's best to open a **feature request issue** …
> Add additional system info

- effects/flag.py
Added Cameroon’s flag
**Summary**
> Update flag.py(added a New flag)

- src/hyperiond/CMakeLists.txt
**Summary**
If Hyperion was built under Windows, the necessary Qt Dlls were missing in the binary folder. Thus Hyperion could not be started in the IDE without copying the Dlls. This has been fixed.
> Deploy Qt DLLs

- README.md
- cmake/Dependencies.cmake
**Summary**
The size of the finished Linux packages (deb, tar.gz) has been reduced by around 41%. This was achieved by removing unnecessary parts from the Python module directory.
> Reduced package size 

- CHANGELOG.md
**Summary**
Update rpi_ws281x to add support for Pi 4 Model B - 2GB v1.4
> Updating rpi_ws281x submodule to latest master

- effects/flag.py
- effects/schema/flag.schema.json
> Update Flag Effect

- assets/webconfig/js/hyperion.js
- assets/webconfig/js/wizard.js
- libsrc/leddevice/dev_net/LedDeviceCololight.cpp
- libsrc/leddevice/dev_net/LedDeviceCololight.h
**Summary**
- Ensure that Cololight can only be saved after identification ran (avoids breaking hyperion)
- Cololight Strip provides number of LEDs, now.
- Consider that a Cololight Strip was cut to a lower number of LEDs …
> Cololight Improvements

- assets/webconfig/js/ui_utils.js
- libsrc/hyperion/SettingsManager.cpp
**Summary**
- Fix #1186: Handle Array & Object configuration elements differently
- Fix UI: Handle error scenario properly, when last last instance number used does not exist any longer.
Fixes #1186
> Fix #1186 & UI last instance error

- cmake/Dependencies.cmake
- include/grabber/DirectXGrabber.h
- libsrc/grabber/directx/DirectXGrabber.cpp
**Summary**
This is a temporary fix for issue #1190. Consideration of Adapter and its displays will be made in a separate PR.
Fixes: #1190
> DirectX9 display change

- assets/webconfig/js/content_leds.js
- libsrc/leddevice/dev_serial/ProviderRs232.cpp
- libsrc/leddevice/dev_serial/ProviderRs232.h
**Summary**
Add udev support for Serial-Devices
Fixes #943
> Serial-Devices - Add udev support

- CHANGELOG.md
- effects/flag.py
- effects/schema/flag.schema.json
**Summary**
convincing reason for adding this feature: UEFA Euro 2020 is ongoing and England and Scotland are participating
> Add British flags to the Flag effect

- assets/webconfig/js/content_effectsconfigurator.js
- assets/webconfig/js/content_general.js
- assets/webconfig/js/content_logging.js
- assets/webconfig/js/content_network.js
- assets/webconfig/js/ui_utils.js
**Summary**
- Escape XSS payload to avoid execution
Fixes #1292
> Fix 1292 - Avoid XSS

- config/hyperion.config.json.default
- include/hyperion/Hyperion.h
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/LinearColorSmoothing.cpp
- libsrc/hyperion/LinearColorSmoothing.h
- libsrc/hyperion/schema/schema-smoothing.json
**Summary**
- Fix that Soothing with "Continuous Updates" disabled does not provides LED updates
- Removed "Continuous Updates" flag as it is obsolete. 
In case an LED-device requires continuous updates, use the LED-Device's "Rewrite Time" parameter.
- New: Smoothing is paused when no input source is available (to save resources)
To avoid wasting …
> Smoothing Fixes, Optimizations

- .github/workflows/apt.json
- CHANGELOG.md
**Summary**
Tested the apt package on an RPi 3B+ running OSMC.
Encountered
> QSqlDatabase: QSQLITE driver not loaded
> QSqlDatabase: available drivers:
> 2021-08-13T23:26:11.873 hyperiond DB : Driver not loaded Driver not loaded
> 2021-08-13T23:26:11.874 hyperiond MAIN : Hyperion Daemon aborted: Failed to open database connection!
> 2021-08-13T23:26:11.874 hyperiond MAIN : Hyperion aborted: Failed to open database connection!
Fixed with
`sudo apt-get install libqt5sql5-sqlite`
**The PR fulfills these …
> Fix libqt5sql5-sqlite packaging dependancy.

- CHANGELOG.md
- assets/webconfig/js/content_leds.js
- assets/webconfig/js/content_network.js
- libsrc/hyperion/SettingsManager.cpp
- libsrc/utils/jsonschema/QJsonSchemaChecker.cpp
**Summary**
- Add migration for APA102 protocol fix (#1352)
- Address LGTM findings
- Include all updates since last release in the changelog 
> Prep 2.0.12 Release

- CHANGELOG.md
- include/commandline/DoubleOption.h
- include/commandline/IntOption.h
- include/utils/NetUtils.h
- libsrc/commandline/DoubleOption.cpp
- libsrc/commandline/IntOption.cpp
- libsrc/commandline/Parser.cpp
- src/hyperion-aml/hyperion-aml.cpp
- src/hyperion-dispmanx/hyperion-dispmanx.cpp
- src/hyperion-framebuffer/hyperion-framebuffer.cpp
- src/hyperion-osx/hyperion-osx.cpp
- src/hyperion-qt/hyperion-qt.cpp
- src/hyperion-v4l2/hyperion-v4l2.cpp
- src/hyperion-x11/hyperion-x11.cpp
- src/hyperion-xcb/hyperion-xcb.cpp
- src/hyperiond/main.cpp
**Summary**
- Standalone grabbers: Improved fps help/error text, fixed default address and port
> Fix standalone grabbers

- CHANGELOG.md
- effects/matrix.json
> Use direct URL of GIF file rather than HTML page

- assets/webconfig/js/content_logging.js
- include/hyperion/Hyperion.h
- include/leddevice/LedDevice.h
- include/utils/Logger.h
- include/utils/hyperion.h
- libsrc/api/API.cpp
- libsrc/api/JsonAPI.cpp
- libsrc/api/JsonCB.cpp
- libsrc/blackborder/BlackBorderProcessor.cpp
- libsrc/effectengine/EffectEngine.cpp
- libsrc/forwarder/MessageForwarder.cpp
- libsrc/hyperion/ComponentRegister.cpp
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/HyperionIManager.cpp
- libsrc/hyperion/ImageProcessor.cpp
- libsrc/hyperion/LinearColorSmoothing.cpp
- libsrc/hyperion/PriorityMuxer.cpp
- libsrc/hyperion/SettingsManager.cpp
- libsrc/leddevice/LedDeviceWrapper.cpp
- libsrc/utils/Logger.cpp
**Summary**
- Have the instance number as part of the logline (#910).
In the UI Log the instance is presented as a readable name
- Fixed: Previous log lines are now shown in the Log UI (was only working for Debug before) …
> Logging enhancement / fixes

- .github/workflows/pull-request.yml
- .github/workflows/push-master.yml
- CMakeLists.txt
- HyperionConfig.h.in
- cmake/packages.cmake
- dependencies/CMakeLists.txt
- src/CMakeLists.txt
**Summary**
- Hyperion Light - Allow hyperion-remote as component
- Minor Fixes
> Hyperion Light updates

- libsrc/hyperion/PriorityMuxer.cpp
**Summary**
- Fix Iterator issue on Windows
> Fix Iterator issue on Windows

- README.md
> add hardware support

- README.md
**Summary**
This is a minor fix for a documentation link in the README.
> Fixed documentation link in README

- CHANGELOG.md
- CMakeLists.txt
- README.md
- cmake/Dependencies.cmake
- doc/development/CompileHowto.md
> Fix OSX Bundling

- dependencies/CMakeLists-mbedtls.txt.in
- dependencies/CMakeLists.txt
**Summary**
Ensures reproducible builds (see f.e. https://github.com/Mbed-TLS/mbedtls/issues/6124)
> dependencies: Pin mbedtls to tagged version v3.1.0

- assets/firmware/esp8266/AtmoOrb/AtmoOrb.ino
- assets/firmware/particle/photon/AtmoOrb_UDP.ino
- assets/webconfig/i18n/en.json
- assets/webconfig/js/content_leds.js
- assets/webconfig/js/ui_utils.js
- assets/webconfig/js/wizard.js
- libsrc/hyperion/LinearColorSmoothing.cpp
**Summary**
- Fix Smoothing out of sync when saving
- Only force Smoothing disabled/enabled for new devices
- Re-Add Max/Min Brightness titles
- UI - Fix: Correctly lookup current Instance Name in case instance IDs…
- Fix AtmoOrb firmware image
- Add AtmoOrb firmware image for Particle/Photon
To avoid wasting your time, it's best to open a …
> Fix Smoothing configuration

- assets/webconfig/js/content_effectsconfigurator.js
- assets/webconfig/js/content_network.js
- assets/webconfig/js/lib/jquery.i18n/CLDRPluralRuleParser.js
- assets/webconfig/js/ui_utils.js
- assets/webconfig/js/wizard.js
- include/hyperion/BGEffectHandler.h
- libsrc/hyperion/Hyperion.cpp
- libsrc/leddevice/LedDeviceWrapper.cpp
**Summary**
Fixes
- Queue LED-device switch off and on signals
- address LGTM findings
Update
- Do not switch-off LED-device, if background effect is configured an will kick-in soon
@asturel Thx for …
> Improve Led Device on/off and background effect

- CHANGELOG.md
- libsrc/grabber/video/v4l2/V4L2Grabber.cpp
**Summary**
Fixes SEGFAULT caused by an improper `auto` deduction.
> Fix SEGFAULT in V4L2Grabber

- include/grabber/EncoderThread.h
- libsrc/grabber/video/EncoderThread.cpp
- libsrc/grabber/video/v4l2/V4L2Grabber.cpp
- libsrc/utils/ImageResampler.cpp
**Summary**
- Support 3D processing for v4l2 MJPEG format
- Fix memory leak when transforming
- ImageResampler: Apply only half crop for 3D to maintain crop ratio
> Fix v4l2 MJPEG Processing

- .github/workflows/apt/amd64.json
- .github/workflows/apt/arm64.json
- .github/workflows/apt/armhf.json
- .lgtm.yml
- bin/compile.sh
- doc/development/CompileHowto.md
- include/grabber/EncoderThread.h
- snap/snapcraft.yaml
**Summary**
- Add libjpeg-dev to allow testing LIBJPEG_TURBO_VERSION_NUMBER
(Respective jconfig.h file is not installed in Debian in contrast to ubuntu)
> Add libjpeg-dev to test LIBJPEG_TURBO_VERSION_NUMBER

- assets/webconfig/i18n/en.json
- assets/webconfig/js/content_remote.js
- config/hyperion.config.json.default
- include/hyperion/LinearColorSmoothing.h
- libsrc/hyperion/LinearColorSmoothing.cpp
- libsrc/hyperion/schema/schema-smoothing.json
- libsrc/leddevice/dev_serial/LedDeviceAdalight.cpp
- libsrc/leddevice/dev_serial/LedDeviceAdalight.h
- libsrc/leddevice/dev_serial/ProviderRs232.cpp
- libsrc/leddevice/dev_serial/ProviderRs232.h
**Summary**
***LED-Devices***
- Adalight - Support device feedback, show statistics provided by HyperSerial sketch (updated by @Lord-Grey)
***Fixes***
- Update Color Calibration on Remote Control when settings saved
- Smoothing Remove "ouputrate" as duplicate to update frequency
To avoid wasting your time, it's best to open a **feature request …
> Fixes - Smoothing, Color-Calibration

- libsrc/python/PythonInit.cpp
**Summary**
- Refactor for Python 3.11 deprecated functions
> Refactor for Python 3.11

- include/utils/ColorRgb.h
- include/utils/Process.h
- libsrc/api/JsonAPI.cpp
- libsrc/api/JsonCB.cpp
- libsrc/grabber/video/mediafoundation/MFGrabber.cpp
- libsrc/leddevice/LedDevice.cpp
- libsrc/leddevice/dev_serial/LedDeviceAdalight.cpp
- libsrc/utils/Process.cpp
- src/hyperiond/systray.cpp
**Summary**
- Add instance# in API response (#1504)
- Restart correctly, if running as service (#1368)
- Correct stopEnableAttemptsTimer thread affinity
- Update fallthrough guide
- Qt6 updates
fixes …
> Fixing outstanding issues

- .github/workflows/apt/amd64.json
**Summary**
Fixes: #1579
the package wanted the dependency libpython3.9
but the executable expects libpython3.10
> fix python version on Debian bookworm (fix #1579)

- CHANGELOG.md
- libsrc/utils/jsonschema/QJsonSchemaChecker.cpp
'std::numeric_limits' do need '#include <limits>'
**Summary**
Fix missing Include in QJsonSchemaChecker.
> Fix missing Include

- .github/workflows/apt/amd64.json
- .github/workflows/apt/arm64.json
- .github/workflows/apt/armhf.json
- CHANGELOG.md
> Update dependencies for Debian Bookworm

- assets/webconfig/js/content_leds.js
- libsrc/leddevice/dev_net/LedDeviceWled.cpp
**Summary**
Fix WLED UI handling, if segment streaming is not supported
> Fix WLED non segment streaming

- .github/workflows/nightly.yml
- .github/workflows/pull-request.yml
- .github/workflows/push-master.yml
- dependencies/CMakeLists.txt
**Summary**
- Update to Protobuf 23.4.0
- Check out sub-modules recursively to have 3rd party submodules of protobuf available
- Add defines for 3rd party sub-modules used by protobuf
> Update to Protobuf 23.4.0

- include/hyperion/LedString.h
- include/utils/hyperion.h
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/LedString.cpp
- test/TestImage2LedsMap.cpp
**Summary**
Fixes
-  Non image updates ignored blacklisted LEDs (#1634)
fixes #1634
> Fix non image updates ignore blacklisted leds

- .github/workflows/push_pull.yml
- .github/workflows/qt5_6.yml
- bin/scripts/install_pr.sh
- cmake/package-scripts/prerm
**Summary**
- Retrofit changes done while building 2.0.16 release
- Improve/Fix install_pr script
- deb Package install -Improve systemd daemon handling after updates
> Corrections after release 2.0.16

- src/hyperion-v4l2/hyperion-v4l2.cpp
**Summary**
- hyperion-v4l2 taking screenshot failed
Fixes #1722
> Fix #1722 - hyperion-v4l2 taking screenshot failed

- src/hyperion-aml/CMakeLists.txt
- src/hyperion-framebuffer/CMakeLists.txt
- src/hyperion-remote/CMakeLists.txt
- src/hyperion-v4l2/CMakeLists.txt
- src/hyperiond/CMakeLists.txt
**Summary**
Remove Amlogic historical changes.
They aren't need anymore.
> Remove unused libs for Amlogic platform

- assets/webconfig/js/content_leds.js
**Summary**
- Disable Identify for same serial device to avoid misleading „Access Denied“ error
> Disable Identify for same serial device

- .github/workflows/qt5_6.yml
- libsrc/protoserver/CMakeLists.txt
**Summary**
- Update flatbuffers to 24.3.25
- Update protobuf to 27.1
- Update mbedtls to 3.6.0
- Fix protobuf  Windows build
- [] Bugfix
> Update external modules

- CMakePresets.json
- assets/webconfig/js/hyperion.js
- libsrc/api/JSONRPC_schema/schema-config.json
- libsrc/api/JsonAPI.cpp
**Summary**
Fixes on top of PR #1786 
> Config refactoring fixes

- CONTRIBUTING.md
**Summary**
Commit f98938020a193d2d0f0ba2af0f937d228f9a1593 moved the `CompileHowto.md`. This PR adjusts sources to changes.
> Update `CompileHowto.md` reference

- assets/webconfig/js/content_leds.js
**Summary**
Fix LED layout Preview (#1813)
fixes #1813
> Fix LED layout Preview

- libsrc/leddevice/dev_net/LedDeviceHomeAssistant.cpp
- libsrc/leddevice/dev_net/LedDeviceHomeAssistant.h
- libsrc/leddevice/schemas/schema-homeassistant.json
**Summary**
- Remove „Turn off on black“ in favour of setting brightness = 0 when Black. That better fits the HA Light Implementation.
> HA - Handle Brightness & Black

- libsrc/leddevice/dev_other/LedDeviceFile.cpp
**Summary**
Correct Windows related „/dev/null“ device
> Fix Windows related „/dev/null“ device

- .gitignore
- CHANGELOG.md
- assets/webconfig/content/login.html
- assets/webconfig/js/content_dashboard.js
- assets/webconfig/js/content_general.js
- assets/webconfig/js/content_index.js
- assets/webconfig/js/content_leds.js
- assets/webconfig/js/content_network.js
- assets/webconfig/js/hyperion.js
- assets/webconfig/js/ledsim.js
- assets/webconfig/js/ui_utils.js
- assets/webconfig/js/wizards/LedDevice_philipshue.js
- bin/scripts/build.py
- doc/development/CMakeUserPresets.json
- include/grabber/qt/QtGrabber.h
- include/grabber/x11/X11Grabber.h
- include/grabber/xcb/XcbGrabber.h
- include/hyperion/HyperionIManager.h
- include/hyperion/LinearColorSmoothing.h
- libsrc/api/JsonAPI.cpp
- libsrc/grabber/x11/X11Grabber.cpp
- libsrc/grabber/xcb/XcbGrabber.cpp
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/HyperionIManager.cpp
- libsrc/hyperion/LinearColorSmoothing.cpp
- libsrc/leddevice/dev_net/LedDevicePhilipsHue.cpp
**Summary**
- API:  Downward compatibility - Use first running instance, if no instance was given nor switched to.
- API - Fix getconfig after API clean-up
- CodeQL - Fix Remote property injection
- Refactored: Streamlined the UI code
- UI: Instance listings are sorted, enabled instances are high-lighted in drop-downs 
- UI: LED preview - show instance's name the preview is applicable to
- Fix Hue lights were not started
- Fix Removed stale _logger object 
- Fix Smoothing after thread affinity alignments (#1863)
If yes, please describe the impact and migration path for …
> API - Downward compatibility

- CHANGELOG.md
**Summary**
- Update mbedTLS to v3.6.4, Update flatbuffers to v25.9.23, Update rpi_ws281x library
> Update external libraries
